package com.example.panel.service;

import java.util.List;
import java.util.Map;

record DialogWorkspaceRolloutGovernanceConfig(
        boolean packetRequired,
        boolean ownerSignoffRequired,
        String ownerSignoffBy,
        String ownerSignoffAtRaw,
        long ownerSignoffTtlHours,
        long reviewCadenceDays,
        String reviewCadenceBy,
        String reviewCadenceAtRaw,
        String reviewCadenceNote,
        String reviewDecisionAction,
        String reviewIncidentFollowup,
        List<String> reviewRequiredCriteria,
        List<String> reviewCheckedCriteria,
        boolean reviewDecisionRequired,
        boolean reviewIncidentFollowupRequired,
        boolean reviewFollowupForNonGoRequired,
        String previousDecisionAction,
        String previousDecisionAtRaw,
        long parityExitDays,
        List<String> parityCriticalReasons,
        List<String> legacyOnlyScenarios,
        Map<String, Map<String, Object>> legacyOnlyScenarioMetadata,
        String legacyInventoryReviewedBy,
        String legacyInventoryReviewedAtRaw,
        String legacyInventoryReviewNote,
        String legacyUsageReviewedBy,
        String legacyUsageReviewedAtRaw,
        String legacyUsageReviewNote,
        String legacyUsageDecision,
        long legacyUsageReviewTtlHours,
        Long legacyUsageMaxSharePct,
        Long legacyUsageMinWorkspaceOpenEvents,
        Long legacyUsageMaxShareDeltaPct,
        Long legacyUsageMaxBlockedShareDeltaPct,
        List<String> legacyManualAllowedReasons,
        boolean legacyManualReasonCatalogRequired,
        boolean legacyBlockedReasonsReviewRequired,
        long legacyBlockedReasonsTopN,
        List<String> legacyBlockedReasonsReviewed,
        String legacyBlockedReasonsFollowup,
        boolean legacyUsageDecisionRequired,
        boolean contextContractRequired,
        List<String> contextContractScenarios,
        List<String> contextContractMandatoryFields,
        Map<String, List<String>> contextContractMandatoryFieldsByScenario,
        List<String> contextContractSourceOfTruth,
        Map<String, List<String>> contextContractSourceOfTruthByScenario,
        List<String> contextContractPriorityBlocks,
        Map<String, List<String>> contextContractPriorityBlocksByScenario,
        Map<String, Map<String, String>> contextContractPlaybooks,
        String contextContractReviewedBy,
        String contextContractReviewedAtRaw,
        String contextContractReviewNote,
        long contextContractReviewTtlHours
) {
}
