package com.example.panel.service;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.mock;

import com.example.panel.config.ObjectsSqliteDataSourceProperties;
import com.example.panel.config.PanelDatabaseRuntimeMode;
import com.example.panel.storage.ObjectPassportPhotoStorageService;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;
import javax.sql.DataSource;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.mock.env.MockEnvironment;

class ObjectPassportAppealMatchingTest {

    @TempDir
    Path tempDir;

    @Test
    void casesPreferLocationAndDeduplicateTicketMessagesWhenCityFormattingDiffers() throws Exception {
        DataSource dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:passport_cases_" + System.nanoTime() + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1", "sa", "");
        JdbcTemplate jdbc = new JdbcTemplate(dataSource);
        jdbc.execute("CREATE TABLE objects (id BIGINT PRIMARY KEY, name VARCHAR(255), address VARCHAR(255), created_at VARCHAR(64))");
        jdbc.execute("CREATE TABLE object_passports (id BIGINT PRIMARY KEY, object_id BIGINT, passport_number VARCHAR(255), details CLOB, created_at VARCHAR(64))");
        jdbc.execute("CREATE TABLE messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ticket_id VARCHAR(255), business VARCHAR(255), city VARCHAR(255), location_name VARCHAR(255), problem VARCHAR(2000), created_at VARCHAR(64))");

        ObjectMapper mapper = new ObjectMapper();
        Map<String, Object> details = Map.of(
                "business", "БлинБери",
                "city", "Волгоград",
                "department", "7 Гвардейская",
                "equipment", List.of(
                        Map.of("equipment_type", "Router", "vendor", "MikroTik", "model", "RB5009"),
                        Map.of("equipment_type", "Router", "vendor", "MikroTik", "model", "RB5009")
                )
        );
        jdbc.update("INSERT INTO objects(id, name, address, created_at) VALUES (1, '7 Гвардейская', 'Ленина 43в', '')");
        jdbc.update("INSERT INTO object_passports(id, object_id, passport_number, details, created_at) VALUES (893, 1, '7 Гвардейская', ?, '')", mapper.writeValueAsString(details));
        jdbc.update("INSERT INTO messages(ticket_id,business,city,location_name,problem,created_at) VALUES ('T-1','БлинБери','г.Волгоград','7 Гвардейская','Первое','2026-09-08T09:00:00')");
        jdbc.update("INSERT INTO messages(ticket_id,business,city,location_name,problem,created_at) VALUES ('T-1','БлинБери','Волгоград','7 Гвардейская','Второе','2026-09-08T10:00:00')");
        jdbc.update("INSERT INTO messages(ticket_id,business,city,location_name,problem,created_at) VALUES ('T-2','БлинБери','город Волгоград','7 Гвардейская','Третье','2026-09-08T11:00:00')");

        ObjectsSqliteDataSourceProperties properties = new ObjectsSqliteDataSourceProperties();
        properties.setPath(tempDir.resolve("objects.db").toString());
        ObjectPassportService service = new ObjectPassportService(
                dataSource,
                properties,
                new PanelDatabaseRuntimeMode(new MockEnvironment()
                        .withProperty("app.datasource.mode", "postgresql")
                        .withProperty("spring.datasource.url", "jdbc:postgresql://localhost:5432/iguana")
                        .withProperty("spring.datasource.username", "iguana")
                        .withProperty("spring.datasource.password", "iguana")),
                jdbc,
                mapper,
                mock(ObjectPassportPhotoStorageService.class)
        );

        Map<String, Object> casesPayload = service.getEmptyCasesPayload(893);
        assertThat((List<?>) casesPayload.get("items")).hasSize(2);
        assertThat(service.listPassports()).singleElement().satisfies(item -> assertThat(item.get("appeals_count")).isEqualTo(2L));

        List<Map<String, Object>> candidates = service.listEquipmentCatalogCandidates();
        assertThat(candidates).hasSize(1);
        assertThat(candidates.get(0).get("equipment_model")).isEqualTo("RB5009");
        assertThat(candidates.get(0).get("usage_count")).isEqualTo(2);
    }
}
