package com.example.panel.service;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.mock;

import com.example.panel.config.ObjectsSqliteDataSourceProperties;
import com.example.panel.config.PanelDatabaseRuntimeMode;
import com.example.panel.storage.ObjectPassportPhotoStorageService;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.nio.file.Path;
import javax.sql.DataSource;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.mock.env.MockEnvironment;

class ObjectPassportServiceRuntimeDataSourceTest {

    @TempDir
    Path tempDir;

    @Test
    void listPassportsUsesPrimaryDatasourceInExternalMode() {
        DataSource primaryDataSource = new DriverManagerDataSource(
            "jdbc:h2:mem:object_passports_service_" + System.nanoTime() + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1",
            "sa",
            ""
        );
        JdbcTemplate jdbcTemplate = new JdbcTemplate(primaryDataSource);
        jdbcTemplate.execute("""
            CREATE TABLE objects (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR(255),
                address VARCHAR(255),
                created_at VARCHAR(64)
            )
            """);
        jdbcTemplate.execute("""
            CREATE TABLE object_passports (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                object_id BIGINT,
                passport_number VARCHAR(255),
                details CLOB,
                created_at VARCHAR(64)
            )
            """);
        jdbcTemplate.execute("""
            CREATE TABLE messages (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ticket_id VARCHAR(255),
                business VARCHAR(255),
                city VARCHAR(255),
                location_name VARCHAR(255)
            )
            """);

        ObjectsSqliteDataSourceProperties properties = new ObjectsSqliteDataSourceProperties();
        properties.setPath(tempDir.resolve("objects.db").toString());
        ObjectPassportService service = new ObjectPassportService(
            primaryDataSource,
            properties,
            new PanelDatabaseRuntimeMode(new MockEnvironment()
                .withProperty("app.datasource.mode", "postgresql")
                .withProperty("spring.datasource.url", "jdbc:postgresql://localhost:5432/iguana")
                .withProperty("spring.datasource.username", "iguana")
                .withProperty("spring.datasource.password", "iguana")),
            jdbcTemplate,
            new ObjectMapper(),
            mock(ObjectPassportPhotoStorageService.class)
        );

        assertThat(service.listPassports()).isEmpty();
    }
}
