package com.example.panel.service;

import com.example.panel.passports.ObjectPassportService;
import com.example.panel.support.PostgresqlJdbcTestSupport;
import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.mock;

import com.example.panel.storage.ObjectPassportPhotoStorageService;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.List;
import java.util.Map;
import javax.sql.DataSource;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;

class ObjectPassportAppealMatchingTest {

    @Test
    void casesPreferLocationAndDeduplicateTicketMessagesWhenCityFormattingDiffers() throws Exception {
        JdbcTemplate jdbc = PostgresqlJdbcTestSupport.freshJdbcTemplate("passport_cases");
        DataSource dataSource = jdbc.getDataSource();
        jdbc.execute("CREATE TABLE objects (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL, address TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP)");
        jdbc.execute("CREATE TABLE object_passports (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, object_id BIGINT NOT NULL REFERENCES objects(id), passport_number TEXT, details TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP)");
        jdbc.execute("CREATE TABLE messages (group_msg_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ticket_id TEXT, business TEXT, city TEXT, location_name TEXT, problem TEXT, created_at TIMESTAMPTZ)");

        ObjectMapper mapper = new ObjectMapper();
        Map<String, Object> details = Map.of(
                "business", "БлинБери",
                "city", "Волгоград",
                "department", "7 Гвардейская",
                "equipment", List.of(
                        Map.of("equipment_type", "Router", "vendor", "MikroTik", "model", "RB5009", "catalog_id", 77),
                        Map.of("equipment_type", "Router", "vendor", "MikroTik", "model", "RB5009"),
                        Map.of("equipment_type", "Router", "vendor", "Legacy", "model", "Old-Router", "archived", true)
                )
        );
        jdbc.update("INSERT INTO objects(id, name, address, created_at) VALUES (1, '7 Гвардейская', 'Ленина 43в', CURRENT_TIMESTAMP)");
        jdbc.update("INSERT INTO object_passports(id, object_id, passport_number, details, created_at) VALUES (893, 1, '7 Гвардейская', ?, CURRENT_TIMESTAMP)", mapper.writeValueAsString(details));
        jdbc.update("INSERT INTO messages(ticket_id,business,city,location_name,problem,created_at) VALUES ('T-1','БлинБери','г.Волгоград','7 Гвардейская','Первое','2026-09-08T09:00:00')");
        jdbc.update("INSERT INTO messages(ticket_id,business,city,location_name,problem,created_at) VALUES ('T-1','БлинБери','Волгоград','7 Гвардейская','Второе','2026-09-08T10:00:00')");
        jdbc.update("INSERT INTO messages(ticket_id,business,city,location_name,problem,created_at) VALUES ('T-2','БлинБери','город Волгоград','7 Гвардейская','Третье','2026-09-08T11:00:00')");

        ObjectPassportService service = new ObjectPassportService(
                dataSource,
                jdbc,
                mapper,
                mock(ObjectPassportPhotoStorageService.class)
        );

        Map<String, Object> casesPayload = service.getEmptyCasesPayload(893);
        assertThat((List<?>) casesPayload.get("items")).hasSize(2);
        assertThat(service.listPassports()).singleElement().satisfies(item -> assertThat(item.get("appeals_count")).isEqualTo(2L));

        List<Map<String, Object>> candidates = service.listEquipmentCatalogCandidates();
        assertThat(candidates).hasSize(1);
        assertThat(candidates.get(0).get("equipment_model")).isEqualTo("RB5009");
        assertThat(candidates.get(0).get("usage_count")).isEqualTo(2);
        assertThat(candidates.get(0).get("object_count")).isEqualTo(1);
        assertThat(candidates.get(0).get("catalog_ids")).isEqualTo(List.of(77L));
        assertThat(candidates).noneMatch(item -> "Old-Router".equals(item.get("equipment_model")));
    }
}
