package com.example.panel.service;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import com.example.panel.storage.ObjectPassportPhotoStorageService;
import com.example.panel.storage.ObjectPassportPhotoStorageService.StoredPhoto;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.Map;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.mock.web.MockMultipartFile;

class SettingsItEquipmentPhotoServiceTest {

    @Test
    void photosRequireCommentSupportMultipleItemsAndKeepSingleTitle() throws Exception {
        DriverManagerDataSource dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:equipment_photos_" + System.nanoTime() + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1", "sa", "");
        JdbcTemplate jdbc = new JdbcTemplate(dataSource);
        jdbc.execute("""
                CREATE TABLE it_equipment_catalog (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    equipment_type VARCHAR(255) NOT NULL,
                    equipment_vendor VARCHAR(255) NOT NULL,
                    equipment_model VARCHAR(255) NOT NULL,
                    photo_url CLOB,
                    serial_number VARCHAR(255),
                    accessories CLOB,
                    created_at TIMESTAMP,
                    updated_at TIMESTAMP
                )
                """);
        jdbc.update("INSERT INTO it_equipment_catalog(equipment_type,equipment_vendor,equipment_model,photo_url) VALUES ('CAMERA','Trassir','TR-1','')");

        ObjectPassportPhotoStorageService storage = mock(ObjectPassportPhotoStorageService.class);
        when(storage.store(any())).thenReturn(
                new StoredPhoto("front.jpg", "front-1.jpg", "/unused/front-1.jpg", "image/jpeg", 100L, "2026-09-08T17:00:00Z"),
                new StoredPhoto("rear.jpg", "rear-2.jpg", "/unused/rear-2.jpg", "image/jpeg", 120L, "2026-09-08T17:01:00Z")
        );
        ObjectMapper mapper = new ObjectMapper();
        SettingsItEquipmentPhotoService service = new SettingsItEquipmentPhotoService(jdbc, mapper, storage);
        MockMultipartFile file = new MockMultipartFile("file", "front.jpg", "image/jpeg", new byte[]{1, 2, 3});

        Map<String, Object> invalid = service.uploadPhoto(1L, file, "title", "");
        assertThat(invalid.get("success")).isEqualTo(false);

        Map<String, Object> first = service.uploadPhoto(1L, file, "title", "Вид спереди");
        assertThat(first.get("success")).isEqualTo(true);
        MockMultipartFile secondFile = new MockMultipartFile("file", "rear.jpg", "image/jpeg", new byte[]{4, 5, 6});
        Map<String, Object> second = service.uploadPhoto(1L, secondFile, "title", "Вид сзади");
        assertThat(second.get("success")).isEqualTo(true);

        String raw = jdbc.queryForObject("SELECT photo_url FROM it_equipment_catalog WHERE id = 1", String.class);
        JsonNode media = mapper.readTree(raw);
        assertThat(media.path("version").asInt()).isEqualTo(2);
        assertThat(media.path("photos").size()).isEqualTo(2);
        assertThat(media.path("photos").findValuesAsText("category")).containsExactlyInAnyOrder("general", "title");
        assertThat(media.path("photos").findValuesAsText("comment")).contains("Вид спереди", "Вид сзади");

        String withLink = service.mergeLinksPreservingPhotos(raw, "[\"https://docs.example/camera\"]");
        JsonNode merged = mapper.readTree(withLink);
        assertThat(merged.path("links").get(0).asText()).isEqualTo("https://docs.example/camera");
        assertThat(merged.path("photos").size()).isEqualTo(2);

        String firstPhotoId = merged.path("photos").get(0).path("id").asText();
        Map<String, Object> deleted = service.deletePhoto(1L, firstPhotoId);
        assertThat(deleted.get("success")).isEqualTo(true);
        verify(storage).deleteQuietly("front-1.jpg");
    }
}
