package com.example.panel.service;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

class SettingsItEquipmentServiceTest {

    @Test
    void listIncludesDiscoveredPassportModelsAndPromotionAllowsMissingVendor() {
        DriverManagerDataSource dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:equipment_catalog_" + System.nanoTime() + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1", "sa", "");
        JdbcTemplate jdbc = new JdbcTemplate(dataSource);
        jdbc.execute("""
                CREATE TABLE it_equipment_catalog (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    equipment_type VARCHAR(255) NOT NULL,
                    equipment_vendor VARCHAR(255) NOT NULL,
                    equipment_model VARCHAR(255) NOT NULL,
                    photo_url CLOB,
                    serial_number VARCHAR(255),
                    accessories CLOB,
                    created_at TIMESTAMP,
                    updated_at TIMESTAMP
                )
                """);
        ObjectPassportService passportService = mock(ObjectPassportService.class);
        when(passportService.listEquipmentCatalogCandidates()).thenReturn(List.of(Map.of(
                "equipment_type", "POS",
                "equipment_vendor", "",
                "equipment_model", "MiniPC",
                "usage_count", 7,
                "object_count", 3,
                "discovered", true,
                "source", "passports"
        )));
        SettingsItEquipmentService service = new SettingsItEquipmentService(
                jdbc, mock(NotificationRoutingService.class), passportService);

        Map<String, Object> before = service.listItEquipment();
        List<?> itemsBefore = (List<?>) before.get("items");
        assertThat(itemsBefore).hasSize(1);
        assertThat(((Map<?, ?>) itemsBefore.get(0)).get("discovered")).isEqualTo(true);
        assertThat(((Map<?, ?>) itemsBefore.get(0)).get("object_count")).isEqualTo(3);

        Map<String, Object> created = service.createItEquipment(Map.of(
                "equipment_type", "POS",
                "equipment_vendor", "",
                "equipment_model", "MiniPC"
        ), "operator");
        assertThat(created.get("success")).isEqualTo(true);
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM it_equipment_catalog", Integer.class)).isEqualTo(1);
        List<?> itemsAfter = (List<?>) created.get("items");
        assertThat(itemsAfter).hasSize(1);
        assertThat(((Map<?, ?>) itemsAfter.get(0)).get("discovered")).isEqualTo(false);
        assertThat(((Map<?, ?>) itemsAfter.get(0)).get("usage_count")).isEqualTo(7);
        assertThat(((Map<?, ?>) itemsAfter.get(0)).get("object_count")).isEqualTo(3);
    }
}
