package com.example.panel.service;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import com.example.panel.storage.ObjectPassportPhotoStorageService;
import com.example.panel.storage.ObjectPassportPhotoStorageService.StoredPhoto;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.Map;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.mock.web.MockMultipartFile;

class SettingsItEquipmentPhotoServiceTest {

    @Test
    void appendsMultiplePhotosGuardsSingleTitleReplacesBinaryAndPromotesFallback() throws Exception {
        DriverManagerDataSource dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:equipment_photos_" + System.nanoTime() + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1", "sa", "");
        JdbcTemplate jdbc = new JdbcTemplate(dataSource);
        jdbc.execute("""
                CREATE TABLE it_equipment_catalog (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    equipment_type VARCHAR(255) NOT NULL,
                    equipment_vendor VARCHAR(255) NOT NULL,
                    equipment_model VARCHAR(255) NOT NULL,
                    photo_url CLOB,
                    serial_number VARCHAR(255),
                    accessories CLOB,
                    created_at TIMESTAMP,
                    updated_at TIMESTAMP
                )
                """);
        jdbc.update("INSERT INTO it_equipment_catalog(equipment_type,equipment_vendor,equipment_model,photo_url) VALUES ('CAMERA','Trassir','TR-1','')");

        ObjectPassportPhotoStorageService storage = mock(ObjectPassportPhotoStorageService.class);
        when(storage.store(any())).thenReturn(
                new StoredPhoto("front.jpg", "front-1.jpg", "/unused/front-1.jpg", "image/jpeg", 100L, "2026-09-09T07:00:00Z"),
                new StoredPhoto("side.jpg", "side-2.jpg", "/unused/side-2.jpg", "image/jpeg", 110L, "2026-09-09T07:01:00Z"),
                new StoredPhoto("rear.jpg", "rear-3.jpg", "/unused/rear-3.jpg", "image/jpeg", 120L, "2026-09-09T07:02:00Z"),
                new StoredPhoto("side-new.webp", "side-new-4.webp", "/unused/side-new-4.webp", "image/webp", 130L, "2026-09-09T07:03:00Z")
        );
        ObjectMapper mapper = new ObjectMapper();
        SettingsItEquipmentPhotoService service = new SettingsItEquipmentPhotoService(jdbc, mapper, storage);

        MockMultipartFile front = new MockMultipartFile("file", "front.jpg", "image/jpeg", new byte[]{1, 2, 3});
        MockMultipartFile side = new MockMultipartFile("file", "side.jpg", "image/jpeg", new byte[]{4, 5, 6});
        MockMultipartFile rear = new MockMultipartFile("file", "rear.jpg", "image/jpeg", new byte[]{7, 8, 9});
        MockMultipartFile sideReplacement = new MockMultipartFile("file", "side-new.webp", "image/webp", new byte[]{10, 11, 12});

        Map<String, Object> invalid = service.uploadPhoto(1L, front, "title", "", false);
        assertThat(invalid.get("success")).isEqualTo(false);

        Map<String, Object> first = service.uploadPhoto(1L, front, "title", "Фронт", false);
        assertThat(first.get("success")).isEqualTo(true);

        Map<String, Object> second = service.uploadPhoto(1L, side, "general", "Сбоку", false);
        assertThat(second.get("success")).isEqualTo(true);
        JsonNode afterSecond = mapper.readTree((String) second.get("photo_url"));
        assertThat(afterSecond.path("photos").size()).isEqualTo(2);
        assertThat(afterSecond.path("photos").findValuesAsText("comment")).containsExactly("Фронт", "Сбоку");

        Map<String, Object> blockedTitle = service.uploadPhoto(1L, rear, "title", "Сзади", false);
        assertThat(blockedTitle.get("success")).isEqualTo(false);
        assertThat(blockedTitle.get("requires_confirmation")).isEqualTo(true);
        assertThat(blockedTitle.get("error_code")).isEqualTo("title_photo_exists");
        verify(storage, times(2)).store(any());

        Map<String, Object> third = service.uploadPhoto(1L, rear, "title", "Сзади", true);
        assertThat(third.get("success")).isEqualTo(true);
        JsonNode afterThird = mapper.readTree((String) third.get("photo_url"));
        assertThat(afterThird.path("photos").size()).isEqualTo(3);
        assertThat(afterThird.path("photos").findValuesAsText("category"))
                .containsExactlyInAnyOrder("general", "general", "title");

        String firstId = afterThird.path("photos").get(0).path("id").asText();
        String secondId = afterThird.path("photos").get(1).path("id").asText();
        String thirdId = afterThird.path("photos").get(2).path("id").asText();

        Map<String, Object> replaced = service.replacePhoto(
                1L, secondId, sideReplacement, "general", "Сбоку после замены", false);
        assertThat(replaced.get("success")).isEqualTo(true);
        JsonNode afterReplace = mapper.readTree((String) replaced.get("photo_url"));
        assertThat(afterReplace.path("photos").size()).isEqualTo(3);
        JsonNode replacedNode = null;
        for (JsonNode photo : afterReplace.path("photos")) {
            if (secondId.equals(photo.path("id").asText())) {
                replacedNode = photo;
                break;
            }
        }
        assertThat(replacedNode).isNotNull();
        assertThat(replacedNode.path("stored_name").asText()).isEqualTo("side-new-4.webp");
        assertThat(replacedNode.path("comment").asText()).isEqualTo("Сбоку после замены");
        verify(storage).deleteQuietly("side-2.jpg");

        Map<String, Object> blockedEdit = service.updatePhoto(1L, firstId, "title", "Новый фронт", false);
        assertThat(blockedEdit.get("requires_confirmation")).isEqualTo(true);

        Map<String, Object> edited = service.updatePhoto(1L, firstId, "title", "Новый фронт", true);
        assertThat(edited.get("success")).isEqualTo(true);
        JsonNode afterEdit = mapper.readTree((String) edited.get("photo_url"));
        assertThat(afterEdit.path("photos").findValuesAsText("category"))
                .containsExactlyInAnyOrder("title", "general", "general");

        Map<String, Object> deleted = service.deletePhoto(1L, firstId);
        assertThat(deleted.get("success")).isEqualTo(true);
        assertThat(deleted.get("promoted_photo_id")).isEqualTo(secondId);
        JsonNode afterDelete = mapper.readTree((String) deleted.get("photo_url"));
        assertThat(afterDelete.path("photos").size()).isEqualTo(2);
        assertThat(afterDelete.path("photos").findValuesAsText("category"))
                .containsExactlyInAnyOrder("title", "general");
        assertThat(afterDelete.path("photos").findValuesAsText("id")).contains(secondId, thirdId);
        verify(storage).deleteQuietly("front-1.jpg");
        verify(storage, times(4)).store(any());

        Map<String, Object> linked = service.updateLinksPreservingPhotos(
                1L, "[\"https://docs.example/camera\"]");
        assertThat(linked.get("success")).isEqualTo(true);
        JsonNode afterLinks = mapper.readTree((String) linked.get("photo_url"));
        assertThat(afterLinks.path("links").get(0).asText()).isEqualTo("https://docs.example/camera");
        assertThat(afterLinks.path("photos").size()).isEqualTo(2);
    }
}
