package com.example.panel.service;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

class SettingsItEquipmentServiceTest {

    @Test
    void listIncludesDiscoveredPassportModelsAndPromotionAllowsMissingVendor() {
        DriverManagerDataSource dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:equipment_catalog_" + System.nanoTime() + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1", "sa", "");
        JdbcTemplate jdbc = new JdbcTemplate(dataSource);
        jdbc.execute("""
                CREATE TABLE it_equipment_catalog (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    equipment_type VARCHAR(255) NOT NULL,
                    equipment_vendor VARCHAR(255) NOT NULL,
                    equipment_model VARCHAR(255) NOT NULL,
                    photo_url CLOB,
                    serial_number VARCHAR(255),
                    accessories CLOB,
                    created_at TIMESTAMP,
                    updated_at TIMESTAMP
                )
                """);
        ObjectPassportService passportService = mock(ObjectPassportService.class);
        when(passportService.listEquipmentCatalogCandidates()).thenReturn(List.of(Map.of(
                "equipment_type", "POS",
                "equipment_vendor", "",
                "equipment_model", "MiniPC",
                "usage_count", 7,
                "object_count", 3,
                "catalog_ids", List.of(1L),
                "discovered", true,
                "source", "passports"
        )));
        SettingsItEquipmentPhotoService photoService = mock(SettingsItEquipmentPhotoService.class);
        when(photoService.mergeLinksPreservingPhotos(anyString(), anyString()))
                .thenAnswer(invocation -> invocation.getArgument(1));
        SettingsItEquipmentService service = new SettingsItEquipmentService(
                jdbc, mock(NotificationRoutingService.class), passportService, photoService);

        Map<String, Object> before = service.listItEquipment();
        List<?> itemsBefore = (List<?>) before.get("items");
        assertThat(itemsBefore).hasSize(1);
        assertThat(((Map<?, ?>) itemsBefore.get(0)).get("discovered")).isEqualTo(true);
        assertThat(((Map<?, ?>) itemsBefore.get(0)).get("object_count")).isEqualTo(3);

        Map<String, Object> created = service.createItEquipment(Map.of(
                "equipment_type", "POS",
                "equipment_vendor", "",
                "equipment_model", "MiniPC"
        ), "operator");
        assertThat(created.get("success")).isEqualTo(true);
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM it_equipment_catalog", Integer.class)).isEqualTo(1);
        List<?> itemsAfter = (List<?>) created.get("items");
        assertThat(itemsAfter).hasSize(1);
        assertThat(((Map<?, ?>) itemsAfter.get(0)).get("discovered")).isEqualTo(false);
        assertThat(((Map<?, ?>) itemsAfter.get(0)).get("usage_count")).isEqualTo(7);
        assertThat(((Map<?, ?>) itemsAfter.get(0)).get("object_count")).isEqualTo(3);

        when(passportService.listEquipmentCatalogCandidates()).thenReturn(List.of(Map.of(
                "equipment_type", "Legacy POS",
                "equipment_vendor", "",
                "equipment_model", "Old MiniPC",
                "usage_count", 7,
                "object_count", 3,
                "catalog_ids", List.of(1L),
                "discovered", true,
                "source", "passports"
        )));
        Map<String, Object> associated = service.listItEquipment();
        List<?> associatedItems = (List<?>) associated.get("items");
        assertThat(associatedItems).hasSize(1);
        assertThat(((Map<?, ?>) associatedItems.get(0)).get("object_count")).isEqualTo(3);

        Map<String, Object> blocked = service.deleteItEquipment(1L, "operator");
        assertThat(blocked.get("success")).isEqualTo(false);
        assertThat(blocked.get("object_count")).isEqualTo(3);
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM it_equipment_catalog", Integer.class)).isEqualTo(1);

        when(passportService.listEquipmentCatalogCandidates()).thenReturn(List.of());
        Map<String, Object> deleted = service.deleteItEquipment(1L, "operator");
        assertThat(deleted.get("success")).isEqualTo(true);
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM it_equipment_catalog", Integer.class)).isZero();
        verify(photoService).deleteStoredPhotos(anyString());
    }

    @Test
    void updateUsesLockedPhotoLinkMergeInsteadOfSnapshotRewrite() {
        DriverManagerDataSource dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:equipment_catalog_links_" + System.nanoTime() + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1", "sa", "");
        JdbcTemplate jdbc = new JdbcTemplate(dataSource);
        jdbc.execute("""
                CREATE TABLE it_equipment_catalog (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    equipment_type VARCHAR(255) NOT NULL,
                    equipment_vendor VARCHAR(255) NOT NULL,
                    equipment_model VARCHAR(255) NOT NULL,
                    photo_url CLOB,
                    serial_number VARCHAR(255),
                    accessories CLOB,
                    created_at TIMESTAMP,
                    updated_at TIMESTAMP
                )
                """);
        jdbc.update("INSERT INTO it_equipment_catalog(equipment_type,equipment_vendor,equipment_model,photo_url) VALUES ('POS','Vendor','Model','')");

        ObjectPassportService passportService = mock(ObjectPassportService.class);
        when(passportService.listEquipmentCatalogCandidates()).thenReturn(List.of());
        SettingsItEquipmentPhotoService photoService = mock(SettingsItEquipmentPhotoService.class);
        when(photoService.updateLinksPreservingPhotos(1L, "[\"https://docs.example/model\"]"))
                .thenReturn(Map.of("success", true, "photo_url", "{}"));
        SettingsItEquipmentService service = new SettingsItEquipmentService(
                jdbc, mock(NotificationRoutingService.class), passportService, photoService);

        Map<String, Object> listed = service.listItEquipment();
        List<?> listedItems = (List<?>) listed.get("items");
        assertThat(((Map<?, ?>) listedItems.get(0)).get("photo_url")).isInstanceOf(String.class);

        Map<String, Object> result = service.updateItEquipment(1L, Map.of(
                "photo_url", "[\"https://docs.example/model\"]"
        ), "operator");

        assertThat(result.get("success")).isEqualTo(true);
        verify(photoService).updateLinksPreservingPhotos(1L, "[\"https://docs.example/model\"]");
    }

    @Test
    void ordinaryMetadataUpdateDoesNotTouchMediaWhenLinksAreOmitted() {
        DriverManagerDataSource dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:equipment_catalog_metadata_" + System.nanoTime() + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1", "sa", "");
        JdbcTemplate jdbc = new JdbcTemplate(dataSource);
        jdbc.execute("""
                CREATE TABLE it_equipment_catalog (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    equipment_type VARCHAR(255) NOT NULL,
                    equipment_vendor VARCHAR(255) NOT NULL,
                    equipment_model VARCHAR(255) NOT NULL,
                    photo_url CLOB,
                    serial_number VARCHAR(255),
                    accessories CLOB,
                    created_at TIMESTAMP,
                    updated_at TIMESTAMP
                )
                """);
        jdbc.update("INSERT INTO it_equipment_catalog(equipment_type,equipment_vendor,equipment_model,photo_url,serial_number) VALUES ('POS','Vendor','Model','{\"version\":2,\"links\":[],\"photos\":[{\"id\":\"p1\",\"category\":\"title\",\"comment\":\"Front\",\"url\":\"/photos/p1\"}]}','OLD')");

        ObjectPassportService passportService = mock(ObjectPassportService.class);
        when(passportService.listEquipmentCatalogCandidates()).thenReturn(List.of());
        SettingsItEquipmentPhotoService photoService = mock(SettingsItEquipmentPhotoService.class);
        SettingsItEquipmentService service = new SettingsItEquipmentService(
                jdbc, mock(NotificationRoutingService.class), passportService, photoService);

        Map<String, Object> result = service.updateItEquipment(1L, Map.of(
                "serial_number", "NEW"
        ), "operator");

        assertThat(result.get("success")).isEqualTo(true);
        assertThat(jdbc.queryForObject("SELECT serial_number FROM it_equipment_catalog WHERE id = 1", String.class)).isEqualTo("NEW");
        assertThat(jdbc.queryForObject("SELECT photo_url FROM it_equipment_catalog WHERE id = 1", String.class)).contains("\"id\":\"p1\"");
        verify(photoService, org.mockito.Mockito.never()).updateLinksPreservingPhotos(org.mockito.ArgumentMatchers.anyLong(), org.mockito.ArgumentMatchers.anyString());
    }
}
