package com.example.panel.service;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import javax.sql.DataSource;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.doNothing;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

class SettingsParameterServiceTest {

    private JdbcTemplate jdbcTemplate;
    private SharedConfigService sharedConfigService;
    private SettingsCatalogService settingsCatalogService;
    private SettingsParameterService service;

    @BeforeEach
    void setUp() {
        DataSource dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:settings_params_" + System.nanoTime() + ";MODE=PostgreSQL;NON_KEYWORDS=VALUE;DB_CLOSE_DELAY=-1",
                "sa",
                ""
        );
        jdbcTemplate = new JdbcTemplate(dataSource);
        jdbcTemplate.execute("""
                CREATE TABLE settings_parameters (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    param_type VARCHAR(255),
                    value VARCHAR(255),
                    state VARCHAR(255),
                    is_deleted INTEGER,
                    deleted_at TIMESTAMP NULL,
                    extra_json CLOB
                )
                """);

        sharedConfigService = mock(SharedConfigService.class);
        settingsCatalogService = mock(SettingsCatalogService.class);
        when(sharedConfigService.loadLocations()).thenReturn(null);
        doNothing().when(sharedConfigService).saveLocations(org.mockito.ArgumentMatchers.any());
        when(settingsCatalogService.getParameterTypes()).thenReturn(Map.of("role", "Role"));
        when(settingsCatalogService.getParameterDependencies()).thenReturn(Map.of("role", List.of()));

        service = new SettingsParameterService(jdbcTemplate, sharedConfigService, settingsCatalogService, new ObjectMapper());
    }

    @Test
    void createParameterStoresExtraJsonAndReturnsGroupedData() {
        Map<String, Object> result = service.createParameter(Map.of(
                "param_type", "role",
                "value", "Manager",
                "state", "Активен",
                "label", "Менеджер"
        ));

        assertEquals(true, result.get("success"));
        assertEquals(1, jdbcTemplate.queryForObject("SELECT COUNT(*) FROM settings_parameters", Integer.class));

        String extraJson = jdbcTemplate.queryForObject(
                "SELECT extra_json FROM settings_parameters WHERE param_type = 'role' AND value = 'Manager'",
                String.class
        );
        assertTrue(extraJson.contains("\"label\":\"Менеджер\""));

        Map<String, Object> grouped = castMap(result.get("data"));
        List<Map<String, Object>> roles = castList(grouped.get("role"));
        assertEquals(1, roles.size());
        assertEquals("Manager", roles.get(0).get("value"));
    }

    @Test
    void createParameterRejectsDuplicateActiveEntry() {
        Map<String, Object> first = service.createParameter(Map.of(
                "param_type", "role",
                "value", "Manager"
        ));
        Map<String, Object> duplicate = service.createParameter(Map.of(
                "param_type", "role",
                "value", "Manager"
        ));

        assertEquals(true, first.get("success"));
        assertEquals(false, duplicate.get("success"));
        assertEquals("Такая запись уже существует", duplicate.get("error"));
    }

    @SuppressWarnings("unchecked")
    private Map<String, Object> castMap(Object value) {
        return (Map<String, Object>) value;
    }

    @SuppressWarnings("unchecked")
    private List<Map<String, Object>> castList(Object value) {
        return (List<Map<String, Object>>) value;
    }
}
