package com.example.panel.service;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import javax.sql.DataSource;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

class SettingsParameterSharedConfigIntegrationTest {

    @TempDir
    Path tempDir;

    private JdbcTemplate jdbcTemplate;
    private SharedConfigService sharedConfigService;
    private SettingsCatalogService settingsCatalogService;
    private SettingsParameterService service;

    @BeforeEach
    void setUp() {
        DataSource dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:settings_params_integration_" + System.nanoTime() + ";MODE=PostgreSQL;NON_KEYWORDS=VALUE;DB_CLOSE_DELAY=-1",
                "sa",
                ""
        );
        jdbcTemplate = new JdbcTemplate(dataSource);
        jdbcTemplate.execute("""
                CREATE TABLE settings_parameters (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    param_type VARCHAR(255),
                    value VARCHAR(255),
                    state VARCHAR(255),
                    is_deleted INTEGER,
                    deleted_at TIMESTAMP NULL,
                    extra_json CLOB,
                    UNIQUE(param_type, value)
                )
                """);

        sharedConfigService = new SharedConfigService(new ObjectMapper(), tempDir.toString());
        settingsCatalogService = mock(SettingsCatalogService.class);
        when(settingsCatalogService.getParameterTypes()).thenReturn(Map.of(
                "business", "Business",
                "country", "Country",
                "partner_type", "Partner Type",
                "city", "City",
                "department", "Department"
        ));
        when(settingsCatalogService.getParameterDependencies()).thenReturn(Map.of(
                "business", List.of(),
                "country", List.of(),
                "partner_type", List.of("country"),
                "city", List.of("country", "partner_type", "business"),
                "department", List.of("country", "partner_type", "business", "city")
        ));

        service = new SettingsParameterService(
                jdbcTemplate,
                sharedConfigService,
                settingsCatalogService,
                new ObjectMapper()
        );
    }

    @Test
    void createParameterSyncsLocationsJsonFromBusinessCityAndDepartment() {
        service.createParameter(Map.of("param_type", "business", "value", "Retail"));
        service.createParameter(Map.of(
                "param_type", "city",
                "value", "Moscow",
                "dependencies", Map.of(
                        "country", "Россия",
                        "partner_type", "shop",
                        "business", "Retail"
                )
        ));
        service.createParameter(Map.of(
                "param_type", "department",
                "value", "Store 1",
                "dependencies", Map.of(
                        "country", "Россия",
                        "partner_type", "shop",
                        "business", "Retail",
                        "city", "Moscow"
                )
        ));

        JsonNode locations = sharedConfigService.loadLocations();

        assertEquals("Store 1",
                locations.path("tree").path("Retail").path("shop").path("Moscow").get(0).asText());
        assertEquals("Россия",
                locations.path("city_meta").path("Retail::shop::Moscow").path("country").asText());
        assertEquals("shop",
                locations.path("location_meta").path("Retail::shop::Moscow::Store 1").path("partner_type").asText());
    }

    @Test
    void syncParametersFromLocationsPayloadHydratesReferenceParameters() {
        Map<String, Object> locationsPayload = Map.of(
                "tree", Map.of(
                        "Retail", Map.of(
                                "shop", Map.of("Moscow", List.of("Store 1"))
                        )
                ),
                "city_meta", Map.of(
                        "Retail::shop::Moscow", Map.of("country", "Россия", "partner_type", "shop")
                ),
                "location_meta", Map.of(
                        "Retail::shop::Moscow::Store 1", Map.of("country", "Россия", "partner_type", "shop")
                )
        );

        service.syncParametersFromLocationsPayload(locationsPayload);

        assertEquals(5, jdbcTemplate.queryForObject("SELECT COUNT(*) FROM settings_parameters", Integer.class));
        assertEquals(1, jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM settings_parameters WHERE param_type = 'business' AND value = 'Retail'",
                Integer.class
        ));
        assertEquals(1, jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM settings_parameters WHERE param_type = 'partner_type' AND value = 'shop'",
                Integer.class
        ));
        assertEquals(1, jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM settings_parameters WHERE param_type = 'country' AND value = 'Россия'",
                Integer.class
        ));
        assertEquals(1, jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM settings_parameters WHERE param_type = 'city' AND value = 'Moscow'",
                Integer.class
        ));
        assertEquals(1, jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM settings_parameters WHERE param_type = 'department' AND value = 'Store 1'",
                Integer.class
        ));

        String departmentExtra = jdbcTemplate.queryForObject(
                "SELECT extra_json FROM settings_parameters WHERE param_type = 'department' AND value = 'Store 1'",
                String.class
        );
        assertTrue(departmentExtra.contains("\"city\":\"Moscow\""));
        assertTrue(departmentExtra.contains("\"business\":\"Retail\""));
    }

    @Test
    void syncParametersFromLocationsPayloadSkipsDuplicateCityValuesAcrossBusinesses() {
        Map<String, Object> locationsPayload = Map.of(
                "tree", Map.of(
                        "БлинБери", Map.of(
                                "Корпоративная сеть", Map.of("Москва", List.of("Тверская"))
                        ),
                        "СушиВёсла", Map.of(
                                "Корпоративная сеть", Map.of("Москва", List.of("Арбат"))
                        )
                ),
                "city_meta", Map.of(
                        "БлинБери::Корпоративная сеть::Москва", Map.of("country", "Россия", "partner_type", "Корпоративная сеть"),
                        "СушиВёсла::Корпоративная сеть::Москва", Map.of("country", "Россия", "partner_type", "Корпоративная сеть")
                ),
                "location_meta", Map.of(
                        "БлинБери::Корпоративная сеть::Москва::Тверская", Map.of("country", "Россия", "partner_type", "Корпоративная сеть"),
                        "СушиВёсла::Корпоративная сеть::Москва::Арбат", Map.of("country", "Россия", "partner_type", "Корпоративная сеть")
                )
        );

        service.syncParametersFromLocationsPayload(locationsPayload);

        assertEquals(1, jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM settings_parameters WHERE param_type = 'city' AND value = 'Москва'",
                Integer.class
        ));
        assertEquals(2, jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM settings_parameters WHERE param_type = 'department'",
                Integer.class
        ));
    }

    @Test
    void repairLocationsSharedConfigIfNeededRestoresEmptyLocationsJsonFromParameters() {
        service.createParameter(Map.of("param_type", "business", "value", "БлинБери"));
        service.createParameter(Map.of("param_type", "business", "value", "СушиВёсла"));
        service.createParameter(Map.of(
                "param_type", "city",
                "value", "Москва",
                "dependencies", Map.of(
                        "country", "Россия",
                        "partner_type", "Корпоративная сеть",
                        "business", "БлинБери"
                )
        ));
        service.createParameter(Map.of(
                "param_type", "department",
                "value", "Тверская",
                "dependencies", Map.of(
                        "country", "Россия",
                        "partner_type", "Корпоративная сеть",
                        "business", "БлинБери",
                        "city", "Москва"
                )
        ));
        service.createParameter(Map.of(
                "param_type", "department",
                "value", "Арбат",
                "dependencies", Map.of(
                        "country", "Россия",
                        "partner_type", "Корпоративная сеть",
                        "business", "СушиВёсла",
                        "city", "Москва"
                )
        ));

        Map<String, Object> emptyLocations = new LinkedHashMap<>();
        emptyLocations.put("tree", Map.of());
        emptyLocations.put("statuses", Map.of());
        emptyLocations.put("city_meta", Map.of());
        emptyLocations.put("location_meta", Map.of());
        emptyLocations.put("locationsLoaded", false);
        emptyLocations.put("locationsLoadingPromise", null);
        sharedConfigService.saveLocations(emptyLocations);

        assertTrue(service.repairLocationsSharedConfigIfNeeded());

        JsonNode locations = sharedConfigService.loadLocations();
        assertEquals("Тверская",
                locations.path("tree").path("БлинБери").path("Корпоративная сеть").path("Москва").get(0).asText());
        assertEquals("Арбат",
                locations.path("tree").path("СушиВёсла").path("Корпоративная сеть").path("Москва").get(0).asText());
        assertEquals("Россия",
                locations.path("city_meta").path("СушиВёсла::Корпоративная сеть::Москва").path("country").asText());
    }

    @Test
    void normalizeLocationBusinessAliasesIfNeededMergesLegacyBusinessAliasIntoCanonicalName() {
        jdbcTemplate.update(
                "INSERT INTO settings_parameters(param_type, value, state, is_deleted, extra_json) VALUES (?, ?, 'Активен', 0, ?)",
                "business",
                "СушиВесла",
                "{\"dependencies\":{}}"
        );
        jdbcTemplate.update(
                "INSERT INTO settings_parameters(param_type, value, state, is_deleted, extra_json) VALUES (?, ?, 'Активен', 0, ?)",
                "business",
                "СушиВёсла",
                "{\"dependencies\":{}}"
        );
        jdbcTemplate.update(
                "INSERT INTO settings_parameters(param_type, value, state, is_deleted, extra_json) VALUES (?, ?, 'Активен', 0, ?)",
                "city",
                "Москва",
                "{\"dependencies\":{\"country\":\"Россия\",\"partner_type\":\"Корпоративная сеть\",\"business\":\"СушиВесла\"},\"country\":\"Россия\",\"partner_type\":\"Корпоративная сеть\",\"business\":\"СушиВесла\"}"
        );
        jdbcTemplate.update(
                "INSERT INTO settings_parameters(param_type, value, state, is_deleted, extra_json) VALUES (?, ?, 'Активен', 0, ?)",
                "department",
                "Арбат",
                "{\"dependencies\":{\"country\":\"Россия\",\"partner_type\":\"Корпоративная сеть\",\"business\":\"СушиВесла\",\"city\":\"Москва\"},\"country\":\"Россия\",\"partner_type\":\"Корпоративная сеть\",\"business\":\"СушиВесла\",\"city\":\"Москва\"}"
        );

        assertTrue(service.normalizeLocationBusinessAliasesIfNeeded());

        assertEquals(0, jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM settings_parameters WHERE param_type = 'business' AND value = 'СушиВесла' AND is_deleted = 0",
                Integer.class
        ));
        assertEquals(1, jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM settings_parameters WHERE param_type = 'business' AND value = 'СушиВёсла' AND is_deleted = 0",
                Integer.class
        ));

        String cityExtra = jdbcTemplate.queryForObject(
                "SELECT extra_json FROM settings_parameters WHERE param_type = 'city' AND value = 'Москва'",
                String.class
        );
        assertTrue(cityExtra.contains("СушиВёсла"));

        JsonNode locations = sharedConfigService.loadLocations();
        assertTrue(locations.path("tree").path("СушиВесла").isMissingNode()
                || locations.path("tree").path("СушиВесла").isEmpty());
        assertEquals("Арбат",
                locations.path("tree").path("СушиВёсла").path("Корпоративная сеть").path("Москва").get(0).asText());
    }
}
