package com.example.panel.service;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import com.example.panel.storage.ObjectPassportPhotoStorageService;
import com.example.panel.storage.ObjectPassportPhotoStorageService.StoredPhoto;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.Map;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.mock.web.MockMultipartFile;

class SettingsItEquipmentPhotoServiceTest {

    @Test
    void titleReplacementNeedsConfirmationMetadataCanBeEditedAndDeletePromotesFallbackTitle() throws Exception {
        DriverManagerDataSource dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:equipment_photos_" + System.nanoTime() + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1", "sa", "");
        JdbcTemplate jdbc = new JdbcTemplate(dataSource);
        jdbc.execute("""
                CREATE TABLE it_equipment_catalog (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    equipment_type VARCHAR(255) NOT NULL,
                    equipment_vendor VARCHAR(255) NOT NULL,
                    equipment_model VARCHAR(255) NOT NULL,
                    photo_url CLOB,
                    serial_number VARCHAR(255),
                    accessories CLOB,
                    created_at TIMESTAMP,
                    updated_at TIMESTAMP
                )
                """);
        jdbc.update("INSERT INTO it_equipment_catalog(equipment_type,equipment_vendor,equipment_model,photo_url) VALUES ('CAMERA','Trassir','TR-1','')");

        ObjectPassportPhotoStorageService storage = mock(ObjectPassportPhotoStorageService.class);
        when(storage.store(any())).thenReturn(
                new StoredPhoto("front.jpg", "front-1.jpg", "/unused/front-1.jpg", "image/jpeg", 100L, "2026-09-08T17:00:00Z"),
                new StoredPhoto("rear.jpg", "rear-2.jpg", "/unused/rear-2.jpg", "image/jpeg", 120L, "2026-09-08T17:01:00Z")
        );
        ObjectMapper mapper = new ObjectMapper();
        SettingsItEquipmentPhotoService service = new SettingsItEquipmentPhotoService(jdbc, mapper, storage);
        MockMultipartFile firstFile = new MockMultipartFile("file", "front.jpg", "image/jpeg", new byte[]{1, 2, 3});
        MockMultipartFile secondFile = new MockMultipartFile("file", "rear.jpg", "image/jpeg", new byte[]{4, 5, 6});

        Map<String, Object> invalid = service.uploadPhoto(1L, firstFile, "title", "", false);
        assertThat(invalid.get("success")).isEqualTo(false);

        Map<String, Object> first = service.uploadPhoto(1L, firstFile, "title", "Вид спереди", false);
        assertThat(first.get("success")).isEqualTo(true);

        Map<String, Object> blockedReplacement = service.uploadPhoto(1L, secondFile, "title", "Вид сзади", false);
        assertThat(blockedReplacement.get("success")).isEqualTo(false);
        assertThat(blockedReplacement.get("requires_confirmation")).isEqualTo(true);
        assertThat(blockedReplacement.get("error_code")).isEqualTo("title_photo_exists");
        verify(storage, times(1)).store(any());

        Map<String, Object> second = service.uploadPhoto(1L, secondFile, "title", "Вид сзади", true);
        assertThat(second.get("success")).isEqualTo(true);
        verify(storage, times(2)).store(any());

        String raw = jdbc.queryForObject("SELECT photo_url FROM it_equipment_catalog WHERE id = 1", String.class);
        JsonNode media = mapper.readTree(raw);
        assertThat(media.path("version").asInt()).isEqualTo(2);
        assertThat(media.path("photos").size()).isEqualTo(2);
        assertThat(media.path("photos").findValuesAsText("category")).containsExactlyInAnyOrder("general", "title");
        assertThat(media.path("photos").findValuesAsText("comment")).contains("Вид спереди", "Вид сзади");

        String firstPhotoId = media.path("photos").get(0).path("id").asText();
        String secondPhotoId = media.path("photos").get(1).path("id").asText();

        Map<String, Object> blockedEdit = service.updatePhoto(1L, firstPhotoId, "title", "Новый фронт", false);
        assertThat(blockedEdit.get("requires_confirmation")).isEqualTo(true);

        Map<String, Object> edited = service.updatePhoto(1L, firstPhotoId, "title", "Новый фронт", true);
        assertThat(edited.get("success")).isEqualTo(true);
        JsonNode editedMedia = mapper.readTree((String) edited.get("photo_url"));
        assertThat(editedMedia.path("photos").findValuesAsText("comment")).contains("Новый фронт", "Вид сзади");
        assertThat(editedMedia.path("photos").get(0).path("category").asText()).isEqualTo("title");
        assertThat(editedMedia.path("photos").get(1).path("category").asText()).isEqualTo("general");

        Map<String, Object> deleted = service.deletePhoto(1L, firstPhotoId);
        assertThat(deleted.get("success")).isEqualTo(true);
        assertThat(deleted.get("promoted_photo_id")).isEqualTo(secondPhotoId);
        JsonNode deletedMedia = mapper.readTree((String) deleted.get("photo_url"));
        assertThat(deletedMedia.path("photos").size()).isEqualTo(1);
        assertThat(deletedMedia.path("photos").get(0).path("id").asText()).isEqualTo(secondPhotoId);
        assertThat(deletedMedia.path("photos").get(0).path("category").asText()).isEqualTo("title");
        verify(storage).deleteQuietly("front-1.jpg");

        String withLink = service.mergeLinksPreservingPhotos((String) deleted.get("photo_url"), "[\"https://docs.example/camera\"]");
        JsonNode merged = mapper.readTree(withLink);
        assertThat(merged.path("links").get(0).asText()).isEqualTo("https://docs.example/camera");
        assertThat(merged.path("photos").size()).isEqualTo(1);
    }
}
