package com.example.panel.service;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import javax.sql.DataSource;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

class SettingsParameterSharedConfigIntegrationTest {

    @TempDir
    Path tempDir;

    private JdbcTemplate jdbcTemplate;
    private SharedConfigService sharedConfigService;
    private SettingsCatalogService settingsCatalogService;
    private SettingsParameterService service;

    @BeforeEach
    void setUp() {
        DataSource dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:settings_params_integration_" + System.nanoTime() + ";MODE=PostgreSQL;NON_KEYWORDS=VALUE;DB_CLOSE_DELAY=-1",
                "sa",
                ""
        );
        jdbcTemplate = new JdbcTemplate(dataSource);
        jdbcTemplate.execute("""
                CREATE TABLE settings_parameters (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    param_type VARCHAR(255),
                    value VARCHAR(255),
                    state VARCHAR(255),
                    is_deleted INTEGER,
                    deleted_at TIMESTAMP NULL,
                    extra_json CLOB
                )
                """);

        sharedConfigService = new SharedConfigService(new ObjectMapper(), tempDir.toString());
        settingsCatalogService = mock(SettingsCatalogService.class);
        when(settingsCatalogService.getParameterTypes()).thenReturn(Map.of(
                "business", "Business",
                "country", "Country",
                "partner_type", "Partner Type",
                "city", "City",
                "department", "Department"
        ));
        when(settingsCatalogService.getParameterDependencies()).thenReturn(Map.of(
                "business", List.of(),
                "country", List.of(),
                "partner_type", List.of("country"),
                "city", List.of("country", "partner_type", "business"),
                "department", List.of("country", "partner_type", "business", "city")
        ));

        service = new SettingsParameterService(
                jdbcTemplate,
                sharedConfigService,
                settingsCatalogService,
                new ObjectMapper()
        );
    }

    @Test
    void createParameterSyncsLocationsJsonFromBusinessCityAndDepartment() {
        service.createParameter(Map.of("param_type", "business", "value", "Retail"));
        service.createParameter(Map.of(
                "param_type", "city",
                "value", "Moscow",
                "dependencies", Map.of(
                        "country", "Россия",
                        "partner_type", "shop",
                        "business", "Retail"
                )
        ));
        service.createParameter(Map.of(
                "param_type", "department",
                "value", "Store 1",
                "dependencies", Map.of(
                        "country", "Россия",
                        "partner_type", "shop",
                        "business", "Retail",
                        "city", "Moscow"
                )
        ));

        JsonNode locations = sharedConfigService.loadLocations();

        assertEquals("Store 1",
                locations.path("tree").path("Retail").path("shop").path("Moscow").get(0).asText());
        assertEquals("Россия",
                locations.path("city_meta").path("Retail::shop::Moscow").path("country").asText());
        assertEquals("shop",
                locations.path("location_meta").path("Retail::shop::Moscow::Store 1").path("partner_type").asText());
    }

    @Test
    void syncParametersFromLocationsPayloadHydratesReferenceParameters() {
        Map<String, Object> locationsPayload = Map.of(
                "tree", Map.of(
                        "Retail", Map.of(
                                "shop", Map.of("Moscow", List.of("Store 1"))
                        )
                ),
                "city_meta", Map.of(
                        "Retail::shop::Moscow", Map.of("country", "Россия", "partner_type", "shop")
                ),
                "location_meta", Map.of(
                        "Retail::shop::Moscow::Store 1", Map.of("country", "Россия", "partner_type", "shop")
                )
        );

        service.syncParametersFromLocationsPayload(locationsPayload);

        assertEquals(5, jdbcTemplate.queryForObject("SELECT COUNT(*) FROM settings_parameters", Integer.class));
        assertEquals(1, jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM settings_parameters WHERE param_type = 'business' AND value = 'Retail'",
                Integer.class
        ));
        assertEquals(1, jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM settings_parameters WHERE param_type = 'partner_type' AND value = 'shop'",
                Integer.class
        ));
        assertEquals(1, jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM settings_parameters WHERE param_type = 'country' AND value = 'Россия'",
                Integer.class
        ));
        assertEquals(1, jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM settings_parameters WHERE param_type = 'city' AND value = 'Moscow'",
                Integer.class
        ));
        assertEquals(1, jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM settings_parameters WHERE param_type = 'department' AND value = 'Store 1'",
                Integer.class
        ));

        String departmentExtra = jdbcTemplate.queryForObject(
                "SELECT extra_json FROM settings_parameters WHERE param_type = 'department' AND value = 'Store 1'",
                String.class
        );
        assertTrue(departmentExtra.contains("\"city\":\"Moscow\""));
        assertTrue(departmentExtra.contains("\"business\":\"Retail\""));
    }
}
