package com.example.panel.service;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import javax.sql.DataSource;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

class UiPreferenceServiceTest {

    private JdbcTemplate jdbcTemplate;
    private UiPreferenceService service;

    @BeforeEach
    void setUp() {
        DataSource dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:ui_prefs_" + System.nanoTime() + ";MODE=PostgreSQL;NON_KEYWORDS=VALUE;DB_CLOSE_DELAY=-1",
                "sa",
                ""
        );
        jdbcTemplate = new JdbcTemplate(dataSource);
        jdbcTemplate.execute("""
                CREATE TABLE settings_parameters (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    param_type VARCHAR(255),
                    value VARCHAR(255),
                    state VARCHAR(255),
                    is_deleted INTEGER,
                    deleted_at TIMESTAMP NULL,
                    extra_json CLOB
                )
                """);
        service = new UiPreferenceService(jdbcTemplate, new ObjectMapper());
    }

    @Test
    void saveForUserNormalizesBasePreferencesAndPersistsThem() {
        Map<String, Object> saved = service.saveForUser("alice", Map.of(
                "theme", "dark",
                "themePalette", "catppuccin",
                "sidebarPinned", true,
                "uiDensityMode", "compact",
                "sidebarNavOrder", List.of("dialogs", "settings", "dialogs")
        ));

        assertEquals("dark", saved.get("theme"));
        assertEquals("catppuccin", saved.get("themePalette"));
        assertEquals("1", saved.get("sidebarPinned"));
        assertEquals("compact", saved.get("uiDensityMode"));
        assertEquals(List.of("dialogs", "settings"), saved.get("sidebarNavOrder"));

        Map<String, Object> reloaded = service.loadForUser("alice");
        assertEquals(saved, reloaded);
        assertEquals(1, jdbcTemplate.queryForObject("SELECT COUNT(*) FROM settings_parameters", Integer.class));
    }

    @Test
    void saveDialogsTriageForUserNormalizesAliasesAndStoresNestedPayload() {
        service.saveForUser("bob", Map.of("theme", "light", "themePalette", "neo"));

        Map<String, Object> triage = service.saveDialogsTriageForUser("bob", Map.of(
                "view", "sla_critical",
                "sortMode", "sla_priority",
                "slaWindowMinutes", 60,
                "pageSize", "all"
        ));

        assertEquals("sla_critical", triage.get("view"));
        assertEquals("sla_priority", triage.get("sort_mode"));
        assertEquals(60, triage.get("sla_window_minutes"));
        assertEquals("all", triage.get("page_size"));
        assertTrue(String.valueOf(triage.get("updated_at_utc")).contains("T"));

        Map<String, Object> reloaded = service.loadDialogsTriageForUser("bob");
        assertEquals("sla_critical", reloaded.get("view"));
        assertEquals("sla_priority", reloaded.get("sort_mode"));
        assertEquals(60, reloaded.get("sla_window_minutes"));
        assertEquals("all", reloaded.get("page_size"));
    }
}
