package com.example.panel.passports;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import com.fasterxml.jackson.databind.ObjectMapper;
import java.sql.Connection;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import javax.sql.DataSource;
import org.junit.jupiter.api.Test;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.web.server.ResponseStatusException;

class ObjectPassportDetailsQueryTest {

    @Test
    void loadsAndNormalizesPassportDetailsAndPreservesNotFound() throws Exception {
        DataSource dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:passport_details_query_" + System.nanoTime()
                        + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1",
                "sa",
                "");
        JdbcTemplate jdbc = new JdbcTemplate(dataSource);
        jdbc.execute("CREATE TABLE objects (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(255), address VARCHAR(255), created_at VARCHAR(64))");
        jdbc.execute("CREATE TABLE object_passports (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, object_id BIGINT, passport_number VARCHAR(255), details CLOB, created_at VARCHAR(64))");

        ObjectPassportPhotoModel photoModel = new ObjectPassportPhotoModel(
                name -> "/api/object_passports/photos/" + name);
        ObjectPassportPayloadModel payloadModel = new ObjectPassportPayloadModel(photoModel);
        ObjectPassportPersistence persistence = new ObjectPassportPersistence(new ObjectMapper(), payloadModel);
        ObjectPassportDetailsQuery query = new ObjectPassportDetailsQuery(persistence, payloadModel);

        try (Connection connection = dataSource.getConnection()) {
            connection.setAutoCommit(false);
            Map<String, Object> payload = new LinkedHashMap<>();
            payload.put("department", "Dept A");
            payload.put("city", "City A");
            payload.put("photos", List.of(Map.of(
                    "id", "photo-1",
                    "category", "title",
                    "stored_name", "front.jpg")));
            long objectId = persistence.insertObject(connection, payload);
            long passportId = persistence.insertPassport(connection, objectId, payload);
            connection.commit();

            Map<String, Object> result = query.load(connection, passportId);
            assertThat(result).containsEntry("success", true);
            Object rawPassport = result.get("passport");
            assertThat(rawPassport).isInstanceOf(Map.class);
            @SuppressWarnings("unchecked")
            Map<String, Object> passport = (Map<String, Object>) rawPassport;
            assertThat(passport)
                    .containsEntry("id", passportId)
                    .containsEntry("is_new", false)
                    .containsEntry("department", "Dept A")
                    .containsEntry("city", "City A");
            assertThat(passport.get("schedule")).isEqualTo(List.of());
            assertThat(passport.get("tasks")).isEqualTo(List.of());

            Object rawPhotos = passport.get("photos");
            assertThat(rawPhotos).isInstanceOf(List.class);
            List<?> photos = (List<?>) rawPhotos;
            assertThat(photos).hasSize(1);
            @SuppressWarnings("unchecked")
            Map<String, Object> photo = (Map<String, Object>) photos.get(0);
            assertThat(photo)
                    .containsEntry("id", "photo-1")
                    .containsEntry("category", "title")
                    .containsEntry("stored_name", "front.jpg")
                    .containsEntry("url", "/api/object_passports/photos/front.jpg");

            assertThatThrownBy(() -> query.load(connection, passportId + 1000))
                    .isInstanceOf(ResponseStatusException.class)
                    .satisfies(error -> assertThat(((ResponseStatusException) error).getStatusCode())
                            .isEqualTo(HttpStatus.NOT_FOUND));
        }
    }
}
