package com.example.panel.passports;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.mock;

import com.example.panel.storage.ObjectPassportPhotoStorageService;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.example.panel.support.PostgresqlJdbcTestSupport;
import javax.sql.DataSource;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;

class ObjectPassportServiceRuntimeDataSourceTest {

    @Test
    void listPassportsUsesPrimaryDatasource() {
        JdbcTemplate jdbcTemplate = PostgresqlJdbcTestSupport.freshJdbcTemplate("object_passports_service");
        DataSource primaryDataSource = jdbcTemplate.getDataSource();
        jdbcTemplate.execute("""
            CREATE TABLE objects (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name TEXT NOT NULL,
                address TEXT,
                created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
            """);
        jdbcTemplate.execute("""
            CREATE TABLE object_passports (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                object_id BIGINT NOT NULL REFERENCES objects(id),
                passport_number TEXT,
                details TEXT,
                created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
            """);
        jdbcTemplate.execute("""
            CREATE TABLE messages (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ticket_id VARCHAR(255),
                business VARCHAR(255),
                city VARCHAR(255),
                location_name VARCHAR(255)
            )
            """);

        ObjectPassportService service = new ObjectPassportService(
            primaryDataSource,
            jdbcTemplate,
            new ObjectMapper(),
            mock(ObjectPassportPhotoStorageService.class)
        );

        assertThat(service.listPassports()).isEmpty();
    }
}
