package com.example.panel.passports;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.example.panel.support.PostgresqlJdbcTestSupport;
import java.sql.Connection;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.sql.DataSource;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;

class ObjectPassportReplaceAllCommandTest {

    @Test
    void replacesDatabaseRowsReturnsStoredPhotosAndLeavesTransactionOwnershipToCaller() throws Exception {
        JdbcTemplate jdbc = PostgresqlJdbcTestSupport.freshJdbcTemplate("passport_replace_all_command");
        DataSource dataSource = jdbc.getDataSource();
        jdbc.execute("CREATE TABLE objects (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL, address TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP)");
        jdbc.execute("CREATE TABLE object_passports (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, object_id BIGINT NOT NULL REFERENCES objects(id), passport_number TEXT, details TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP)");

        ObjectPassportPhotoModel photoModel = new ObjectPassportPhotoModel(name -> "/photos/" + name);
        ObjectPassportPayloadModel payloadModel = new ObjectPassportPayloadModel(photoModel);
        ObjectPassportPersistence persistence = new ObjectPassportPersistence(new ObjectMapper(), payloadModel);
        ObjectPassportReplaceAllCommand command = new ObjectPassportReplaceAllCommand(
                persistence, payloadModel, photoModel);

        try (Connection connection = dataSource.getConnection()) {
            connection.setAutoCommit(false);
            Map<String, Object> existing = new LinkedHashMap<>();
            existing.put("business", "Business Old");
            existing.put("city", "City Old");
            existing.put("department", "Dept Old");
            existing.put("photos", List.of(
                    Map.of("id", "photo-1", "category", "other", "stored_name", "old-a.jpg"),
                    Map.of("id", "photo-2", "category", "other", "storedName", "old-b.jpg")));
            long oldObjectId = persistence.insertObject(connection, existing);
            persistence.insertPassport(connection, oldObjectId, existing);
            connection.commit();

            Map<String, Object> replacement = Map.of(
                    "business", "Business New",
                    "city", "City New",
                    "department", "Dept New");
            Set<String> firstCleanup = command.replace(connection, List.of(replacement));
            assertThat(connection.getAutoCommit()).isFalse();
            assertThat(firstCleanup).containsExactlyInAnyOrder("old-a.jpg", "old-b.jpg");
            connection.rollback();

            assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM object_passports", Integer.class)).isEqualTo(1);
            assertThat(jdbc.queryForObject("SELECT passport_number FROM object_passports", String.class)).isEqualTo("Dept Old");

            assertThatThrownBy(() -> command.replace(
                    connection, List.of(Map.of("business", "Missing department"))))
                    .isInstanceOf(IllegalArgumentException.class)
                    .hasMessageContaining("Департамент");
            connection.rollback();
            assertThat(jdbc.queryForObject("SELECT passport_number FROM object_passports", String.class)).isEqualTo("Dept Old");

            Set<String> cleanup = command.replace(connection, List.of(replacement));
            assertThat(cleanup).containsExactlyInAnyOrder("old-a.jpg", "old-b.jpg");
            connection.commit();

            assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM objects", Integer.class)).isEqualTo(1);
            assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM object_passports", Integer.class)).isEqualTo(1);
            assertThat(jdbc.queryForObject("SELECT passport_number FROM object_passports", String.class)).isEqualTo("Dept New");
        }
    }
}
