package com.example.panel.passports;

import static org.assertj.core.api.Assertions.assertThat;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.example.panel.support.PostgresqlJdbcTestSupport;
import java.sql.Connection;
import java.util.LinkedHashMap;
import java.util.Map;
import javax.sql.DataSource;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;

class ObjectPassportNetBoxQueryTest {

    @Test
    void findsPassportByNormalizedNetBoxSiteId() throws Exception {
        JdbcTemplate jdbc = PostgresqlJdbcTestSupport.freshJdbcTemplate("passport_netbox_query");
        DataSource dataSource = jdbc.getDataSource();
        jdbc.execute("CREATE TABLE objects (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL, address TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP)");
        jdbc.execute("CREATE TABLE object_passports (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, object_id BIGINT NOT NULL REFERENCES objects(id), passport_number TEXT, details TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP)");

        ObjectPassportPhotoModel photoModel = new ObjectPassportPhotoModel(
                name -> "/api/object_passports/photos/" + name);
        ObjectPassportPayloadModel payloadModel = new ObjectPassportPayloadModel(photoModel);
        ObjectPassportPersistence persistence = new ObjectPassportPersistence(new ObjectMapper(), payloadModel);
        ObjectPassportNetBoxQuery query = new ObjectPassportNetBoxQuery(persistence, payloadModel);

        try (Connection connection = dataSource.getConnection()) {
            connection.setAutoCommit(false);

            Map<String, Object> other = new LinkedHashMap<>();
            other.put("department", "Dept A");
            other.put("netbox_site_id", "159");
            long otherObjectId = persistence.insertObject(connection, other);
            persistence.insertPassport(connection, otherObjectId, other);

            Map<String, Object> target = new LinkedHashMap<>();
            target.put("department", "Dept B");
            target.put("business", "Business B");
            target.put("netbox_site_id", "160");
            long targetObjectId = persistence.insertObject(connection, target);
            long targetPassportId = persistence.insertPassport(connection, targetObjectId, target);
            connection.commit();

            String normalizedSiteId = query.normalizeSiteId("  160  ");
            assertThat(normalizedSiteId).isEqualTo("160");
            assertThat(query.normalizeSiteId("   ")).isEmpty();

            Map<String, Object> found = query.findBySiteId(connection, normalizedSiteId);
            assertThat(found)
                    .containsEntry("id", targetPassportId)
                    .containsEntry("department", "Dept B")
                    .containsEntry("business", "Business B")
                    .containsEntry("netbox_site_id", "160")
                    .containsEntry("is_new", false);
            assertThat(query.findBySiteId(connection, "999")).isNull();
            assertThat(query.findBySiteId(connection, "")).isNull();
        }
    }
}
