package com.example.panel.passports;

import static org.assertj.core.api.Assertions.assertThat;

import com.fasterxml.jackson.databind.ObjectMapper;
import java.sql.Connection;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import javax.sql.DataSource;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

class ObjectPassportPersistenceTest {

    @Test
    void persistsLoadsAndUpdatesRowsThroughDedicatedGateway() throws Exception {
        DataSource dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:passport_persistence_" + System.nanoTime() + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1",
                "sa",
                "");
        JdbcTemplate jdbc = new JdbcTemplate(dataSource);
        jdbc.execute("CREATE TABLE objects (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(255), address VARCHAR(255), created_at VARCHAR(64))");
        jdbc.execute("CREATE TABLE object_passports (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, object_id BIGINT, passport_number VARCHAR(255), details CLOB, created_at VARCHAR(64))");

        ObjectPassportPhotoModel photoModel = new ObjectPassportPhotoModel(name -> "/api/object_passports/photos/" + name);
        ObjectPassportPayloadModel payloadModel = new ObjectPassportPayloadModel(photoModel);
        ObjectPassportPersistence persistence = new ObjectPassportPersistence(new ObjectMapper(), payloadModel);

        try (Connection connection = dataSource.getConnection()) {
            connection.setAutoCommit(false);
            Map<String, Object> payload = new LinkedHashMap<>();
            payload.put("department", "Ленина 1");
            payload.put("city", "Смоленск");
            payload.put("business", "БлинБери");
            payload.put("location_address", "Ленина 1, Смоленск");

            long objectId = persistence.insertObject(connection, payload);
            long passportId = persistence.insertPassport(connection, objectId, payload);
            connection.commit();

            ObjectPassportPersistence.StoredPassportRecord stored = persistence.loadStoredPassport(connection, passportId);
            assertThat(stored.objectId()).isEqualTo(objectId);
            assertThat(stored.payload())
                    .containsEntry("department", "Ленина 1")
                    .containsEntry("city", "Смоленск")
                    .containsEntry("location_address", "Ленина 1, Смоленск");
            assertThat(persistence.loadAllStoredPassports(connection)).hasSize(1);

            Map<String, Object> updated = new LinkedHashMap<>(stored.payload());
            updated.put("department", "Ленина 2");
            updated.put("location_address", "Ленина 2, Смоленск");
            assertThat(persistence.updateObject(connection, objectId, updated)).isTrue();
            persistence.updatePassportRow(connection, passportId, objectId, updated);
            connection.commit();

            ObjectPassportPersistence.StoredPassportRecord reloaded = persistence.loadStoredPassport(connection, passportId);
            assertThat(reloaded.payload())
                    .containsEntry("department", "Ленина 2")
                    .containsEntry("location_address", "Ленина 2, Смоленск");
            assertThat(persistence.readPayload("not-json")).isEmpty();
        }
    }
}
