package com.example.panel.passports;

import static org.assertj.core.api.Assertions.assertThat;

import com.fasterxml.jackson.databind.ObjectMapper;
import java.sql.Connection;
import java.util.LinkedHashMap;
import java.util.Map;
import javax.sql.DataSource;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

class ObjectPassportNetBoxQueryTest {

    @Test
    void findsPassportByNormalizedNetBoxSiteId() throws Exception {
        DataSource dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:passport_netbox_query_" + System.nanoTime() + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1",
                "sa",
                "");
        JdbcTemplate jdbc = new JdbcTemplate(dataSource);
        jdbc.execute("CREATE TABLE objects (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(255), address VARCHAR(255), created_at VARCHAR(64))");
        jdbc.execute("CREATE TABLE object_passports (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, object_id BIGINT, passport_number VARCHAR(255), details CLOB, created_at VARCHAR(64))");

        ObjectPassportPhotoModel photoModel = new ObjectPassportPhotoModel(
                name -> "/api/object_passports/photos/" + name);
        ObjectPassportPayloadModel payloadModel = new ObjectPassportPayloadModel(photoModel);
        ObjectPassportPersistence persistence = new ObjectPassportPersistence(new ObjectMapper(), payloadModel);
        ObjectPassportNetBoxQuery query = new ObjectPassportNetBoxQuery(persistence, payloadModel);

        try (Connection connection = dataSource.getConnection()) {
            connection.setAutoCommit(false);

            Map<String, Object> other = new LinkedHashMap<>();
            other.put("department", "Dept A");
            other.put("netbox_site_id", "159");
            long otherObjectId = persistence.insertObject(connection, other);
            persistence.insertPassport(connection, otherObjectId, other);

            Map<String, Object> target = new LinkedHashMap<>();
            target.put("department", "Dept B");
            target.put("business", "Business B");
            target.put("netbox_site_id", "160");
            long targetObjectId = persistence.insertObject(connection, target);
            long targetPassportId = persistence.insertPassport(connection, targetObjectId, target);
            connection.commit();

            String normalizedSiteId = query.normalizeSiteId("  160  ");
            assertThat(normalizedSiteId).isEqualTo("160");
            assertThat(query.normalizeSiteId("   ")).isEmpty();

            Map<String, Object> found = query.findBySiteId(connection, normalizedSiteId);
            assertThat(found)
                    .containsEntry("id", targetPassportId)
                    .containsEntry("department", "Dept B")
                    .containsEntry("business", "Business B")
                    .containsEntry("netbox_site_id", "160")
                    .containsEntry("is_new", false);
            assertThat(query.findBySiteId(connection, "999")).isNull();
            assertThat(query.findBySiteId(connection, "")).isNull();
        }
    }
}
