package com.example.panel.passports;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import com.fasterxml.jackson.databind.ObjectMapper;
import java.sql.Connection;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import javax.sql.DataSource;
import org.junit.jupiter.api.Test;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.web.server.ResponseStatusException;

class ObjectPassportPhotoQueryTest {

    @Test
    void findsPassportByPhotoIdAndPreservesNormalizedPhotos() throws Exception {
        DataSource dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:passport_photo_query_" + System.nanoTime() + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1",
                "sa",
                "");
        JdbcTemplate jdbc = new JdbcTemplate(dataSource);
        jdbc.execute("CREATE TABLE objects (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(255), address VARCHAR(255), created_at VARCHAR(64))");
        jdbc.execute("CREATE TABLE object_passports (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, object_id BIGINT, passport_number VARCHAR(255), details CLOB, created_at VARCHAR(64))");

        ObjectPassportPhotoModel photoModel = new ObjectPassportPhotoModel(
                name -> "/api/object_passports/photos/" + name);
        ObjectPassportPayloadModel payloadModel = new ObjectPassportPayloadModel(photoModel);
        ObjectPassportPersistence persistence = new ObjectPassportPersistence(new ObjectMapper(), payloadModel);
        ObjectPassportPhotoQuery query = new ObjectPassportPhotoQuery(persistence, photoModel);

        long targetPassportId;
        try (Connection connection = dataSource.getConnection()) {
            connection.setAutoCommit(false);

            Map<String, Object> first = new LinkedHashMap<>();
            first.put("department", "Dept A");
            first.put("photos", List.of(Map.of(
                    "id", "photo-other",
                    "category", "archive",
                    "stored_name", "other.jpg")));
            long firstObjectId = persistence.insertObject(connection, first);
            persistence.insertPassport(connection, firstObjectId, first);

            Map<String, Object> target = new LinkedHashMap<>();
            target.put("department", "Dept B");
            target.put("photos", List.of(Map.of(
                    "id", "photo-target",
                    "category", "title",
                    "stored_name", "target.jpg")));
            long targetObjectId = persistence.insertObject(connection, target);
            targetPassportId = persistence.insertPassport(connection, targetObjectId, target);
            connection.commit();

            ObjectPassportPersistence.StoredPassportRecord found =
                    query.findStoredPassportByPhotoId(connection, "  photo-target  ");

            assertThat(found.passportId()).isEqualTo(targetPassportId);
            assertThat(found.objectId()).isEqualTo(targetObjectId);
            assertThat(found.payload()).containsEntry("department", "Dept B");
            Object rawPhotos = found.payload().get("photos");
            assertThat(rawPhotos).isInstanceOf(List.class);
            List<?> photos = (List<?>) rawPhotos;
            assertThat(photos).hasSize(1);
            Object rawPhoto = photos.get(0);
            assertThat(rawPhoto).isInstanceOf(Map.class);
            Map<?, ?> photo = (Map<?, ?>) rawPhoto;
            assertThat(photo.get("id")).isEqualTo("photo-target");
            assertThat(photo.get("category")).isEqualTo("title");
            assertThat(photo.get("stored_name")).isEqualTo("target.jpg");
            assertThat(photo.get("url")).isEqualTo("/api/object_passports/photos/target.jpg");

            assertPhotoNotFound(() -> query.findStoredPassportByPhotoId(connection, "   "));
            assertPhotoNotFound(() -> query.findStoredPassportByPhotoId(connection, "missing-photo"));
        }
    }

    private void assertPhotoNotFound(ThrowingLookup lookup) {
        assertThatThrownBy(lookup::run)
                .isInstanceOf(ResponseStatusException.class)
                .satisfies(error -> assertThat(((ResponseStatusException) error).getStatusCode())
                        .isEqualTo(HttpStatus.NOT_FOUND));
    }

    @FunctionalInterface
    private interface ThrowingLookup {
        void run() throws Exception;
    }
}
