package com.example.panel.passports;

import static org.assertj.core.api.Assertions.assertThat;

import com.fasterxml.jackson.databind.ObjectMapper;
import java.sql.Connection;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import javax.sql.DataSource;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

class ObjectPassportListQueryTest {

    @Test
    void projectsPassportListRowsThroughDedicatedQuery() throws Exception {
        DataSource dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:passport_list_query_" + System.nanoTime() + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1",
                "sa",
                "");
        JdbcTemplate jdbc = new JdbcTemplate(dataSource);
        jdbc.execute("CREATE TABLE objects (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(255), address VARCHAR(255), created_at VARCHAR(64))");
        jdbc.execute("CREATE TABLE object_passports (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, object_id BIGINT, passport_number VARCHAR(255), details CLOB, created_at VARCHAR(64))");
        jdbc.update("INSERT INTO objects(id, name, address, created_at) VALUES (?, ?, ?, ?)",
                10L, "DB object name", "DB address", "2026-09-16T00:00:00Z");

        Map<String, Object> details = new LinkedHashMap<>();
        details.put("department", "Dept A");
        details.put("city", "City A");
        details.put("business", "Business A");
        details.put("status", "deleted");
        details.put("photos", List.of(Map.of(
                "id", "photo-1",
                "category", "title",
                "stored_name", "hero.jpg")));
        ObjectMapper objectMapper = new ObjectMapper();
        jdbc.update("INSERT INTO object_passports(id, object_id, passport_number, details, created_at) VALUES (?, ?, ?, ?, ?)",
                20L, 10L, "DB-PASS", objectMapper.writeValueAsString(details), "2026-09-16T00:00:00Z");

        ObjectPassportPhotoModel photoModel = new ObjectPassportPhotoModel(
                name -> "/api/object_passports/photos/" + name);
        ObjectPassportPayloadModel payloadModel = new ObjectPassportPayloadModel(photoModel);
        ObjectPassportPersistence persistence = new ObjectPassportPersistence(objectMapper, payloadModel);
        ObjectPassportAppealQuery appealQuery = new ObjectPassportAppealQuery(jdbc);
        ObjectPassportListQuery query = new ObjectPassportListQuery(
                persistence, payloadModel, photoModel, appealQuery);

        List<Map<String, Object>> items;
        try (Connection connection = dataSource.getConnection()) {
            items = query.list(
                    connection,
                    Map.of("department-business::business a::dept a", 7L));
        }

        assertThat(items).hasSize(1);
        Map<String, Object> item = items.get(0);
        assertThat(item)
                .containsEntry("id", 20L)
                .containsEntry("department", "Dept A")
                .containsEntry("city", "City A")
                .containsEntry("business", "Business A")
                .containsEntry("status", "deleted")
                .containsEntry("deleted", true)
                .containsEntry("title_photo_url", "/api/object_passports/photos/hero.jpg")
                .containsEntry("location_address", "DB address")
                .containsEntry("passport_number", "Dept A")
                .containsEntry("object_name", "DB object name")
                .containsEntry("appeals_count", 7L);
        assertThat(item.get("photos")).isInstanceOf(List.class);
        List<?> photos = (List<?>) item.get("photos");
        assertThat(photos).hasSize(1);
        Object rawPhoto = photos.get(0);
        assertThat(rawPhoto).isInstanceOf(Map.class);
        Map<?, ?> photo = (Map<?, ?>) rawPhoto;
        assertThat(photo.get("category")).isEqualTo("title");
        assertThat(photo.get("url")).isEqualTo("/api/object_passports/photos/hero.jpg");
    }
}
