package com.example.panel.passports;

import static org.assertj.core.api.Assertions.assertThat;

import com.fasterxml.jackson.databind.ObjectMapper;
import java.sql.Connection;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import javax.sql.DataSource;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

class ObjectPassportUpdateCommandTest {

    @Test
    void updatesPassportAndKeepsManualOverrideSemanticsSeparateFromExternalUpdates() throws Exception {
        DataSource dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:passport_update_command_" + System.nanoTime()
                        + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1",
                "sa",
                "");
        JdbcTemplate jdbc = new JdbcTemplate(dataSource);
        jdbc.execute("CREATE TABLE objects (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(255), address VARCHAR(255), created_at VARCHAR(64))");
        jdbc.execute("CREATE TABLE object_passports (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, object_id BIGINT, passport_number VARCHAR(255), details CLOB, created_at VARCHAR(64))");

        ObjectPassportPhotoModel photoModel = new ObjectPassportPhotoModel(name -> "/photos/" + name);
        ObjectPassportPayloadModel payloadModel = new ObjectPassportPayloadModel(photoModel);
        ObjectPassportPersistence persistence = new ObjectPassportPersistence(new ObjectMapper(), payloadModel);
        ObjectPassportManualOverrideModel manualOverrideModel = new ObjectPassportManualOverrideModel();
        ObjectPassportUpdateCommand command = new ObjectPassportUpdateCommand(
                persistence, payloadModel, manualOverrideModel);

        try (Connection connection = dataSource.getConnection()) {
            connection.setAutoCommit(false);
            Map<String, Object> initial = new LinkedHashMap<>();
            initial.put("business", "Business A");
            initial.put("city", "City A");
            initial.put("department", "Dept A");
            initial.put("location_address", "Main 1");
            long objectId = persistence.insertObject(connection, initial);
            long passportId = persistence.insertPassport(connection, objectId, initial);
            connection.commit();

            Map<String, Object> manualResult = command.update(
                    connection, passportId, Map.of("city", "City B"), true);
            assertThat(connection.getAutoCommit()).isFalse();
            Object rawManualPassport = manualResult.get("passport");
            assertThat(rawManualPassport).isInstanceOf(Map.class);
            @SuppressWarnings("unchecked")
            Map<String, Object> manualPassport = (Map<String, Object>) rawManualPassport;
            assertThat(manualResult)
                    .containsEntry("success", true)
                    .containsEntry("id", passportId);
            assertThat(manualPassport)
                    .containsEntry("city", "City B")
                    .containsEntry("department", "Dept A")
                    .containsEntry("_manual_overrides", List.of("city"));
            connection.commit();

            Map<String, Object> externalResult = command.update(
                    connection, passportId, Map.of("business", "Business B"), false);
            Object rawExternalPassport = externalResult.get("passport");
            assertThat(rawExternalPassport).isInstanceOf(Map.class);
            @SuppressWarnings("unchecked")
            Map<String, Object> externalPassport = (Map<String, Object>) rawExternalPassport;
            assertThat(externalPassport)
                    .containsEntry("business", "Business B")
                    .containsEntry("city", "City B")
                    .containsEntry("_manual_overrides", List.of("city"));
            connection.commit();

            assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM objects", Integer.class)).isEqualTo(1);
            assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM object_passports", Integer.class)).isEqualTo(1);
            assertThat(jdbc.queryForObject("SELECT passport_number FROM object_passports WHERE id = ?", String.class, passportId))
                    .isEqualTo("Dept A");
        }
    }
}
