package com.example.panel.passports;

import static org.assertj.core.api.Assertions.assertThat;

import com.fasterxml.jackson.databind.ObjectMapper;
import java.sql.Connection;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import javax.sql.DataSource;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

class ObjectPassportPhotoCommandTest {

    @Test
    void updatesAndDeletesPhotosWithoutOwningTransactionOrStorageCleanup() throws Exception {
        DataSource dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:passport_photo_command_" + System.nanoTime()
                        + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1",
                "sa",
                "");
        JdbcTemplate jdbc = new JdbcTemplate(dataSource);
        jdbc.execute("CREATE TABLE objects (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(255), address VARCHAR(255), created_at VARCHAR(64))");
        jdbc.execute("CREATE TABLE object_passports (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, object_id BIGINT, passport_number VARCHAR(255), details CLOB, created_at VARCHAR(64))");

        ObjectPassportPhotoModel photoModel = new ObjectPassportPhotoModel(
                name -> "/api/object_passports/photos/" + name);
        ObjectPassportPayloadModel payloadModel = new ObjectPassportPayloadModel(photoModel);
        ObjectPassportPersistence persistence = new ObjectPassportPersistence(new ObjectMapper(), payloadModel);
        ObjectPassportPhotoQuery photoQuery = new ObjectPassportPhotoQuery(persistence, photoModel);
        ObjectPassportPhotoCommand command = new ObjectPassportPhotoCommand(
                persistence, payloadModel, photoModel, photoQuery);

        try (Connection connection = dataSource.getConnection()) {
            connection.setAutoCommit(false);
            Map<String, Object> initial = new LinkedHashMap<>();
            initial.put("department", "Dept A");
            initial.put("photos", List.of(
                    Map.of(
                            "id", "photo-1",
                            "category", "title",
                            "caption", "Первое",
                            "stored_name", "first.jpg"),
                    Map.of(
                            "id", "photo-2",
                            "category", "archive",
                            "caption", "Второе",
                            "stored_name", "second.jpg")));
            long objectId = persistence.insertObject(connection, initial);
            long passportId = persistence.insertPassport(connection, objectId, initial);
            connection.commit();

            Map<String, Object> updated = command.update(
                    connection,
                    "  photo-2  ",
                    Map.of("caption", "  Новый вид  ", "category", "title"));

            assertThat(connection.getAutoCommit()).isFalse();
            assertThat(updated).containsEntry("success", true);
            List<Map<String, Object>> updatedPhotos = photos(updated.get("photos"));
            assertThat(updatedPhotos).hasSize(2);
            assertThat(updatedPhotos.get(0)).containsEntry("category", "archive");
            assertThat(updatedPhotos.get(1))
                    .containsEntry("id", "photo-2")
                    .containsEntry("category", "title")
                    .containsEntry("caption", "Новый вид");
            connection.commit();

            ObjectPassportPersistence.StoredPassportRecord persistedAfterUpdate =
                    persistence.loadStoredPassport(connection, passportId);
            List<Map<String, Object>> persistedPhotos =
                    photoModel.normalizePhotos(persistedAfterUpdate.payload().get("photos"));
            assertThat(persistedPhotos.get(1))
                    .containsEntry("category", "title")
                    .containsEntry("caption", "Новый вид");

            ObjectPassportPhotoCommand.DeleteResult deletion = command.delete(connection, "photo-2");

            assertThat(connection.getAutoCommit()).isFalse();
            assertThat(deletion.storedName()).isEqualTo("second.jpg");
            assertThat(deletion.response()).containsEntry("success", true);
            List<Map<String, Object>> remaining = photos(deletion.response().get("photos"));
            assertThat(remaining).hasSize(1);
            assertThat(remaining.get(0))
                    .containsEntry("id", "photo-1")
                    .containsEntry("category", "archive");

            connection.rollback();

            ObjectPassportPersistence.StoredPassportRecord persistedAfterRollback =
                    persistence.loadStoredPassport(connection, passportId);
            List<Map<String, Object>> afterRollback =
                    photoModel.normalizePhotos(persistedAfterRollback.payload().get("photos"));
            assertThat(afterRollback).hasSize(2);
            assertThat(afterRollback.get(1))
                    .containsEntry("id", "photo-2")
                    .containsEntry("category", "title")
                    .containsEntry("caption", "Новый вид");
        }
    }

    @SuppressWarnings("unchecked")
    private List<Map<String, Object>> photos(Object raw) {
        return (List<Map<String, Object>>) raw;
    }
}
