package com.example.panel.passports;

import static org.assertj.core.api.Assertions.assertThat;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.example.panel.support.PostgresqlJdbcTestSupport;
import java.sql.Connection;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import javax.sql.DataSource;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;

class ObjectPassportEquipmentCatalogQueryTest {

    @Test
    void loadsAndAggregatesEquipmentCandidatesFromStoredPassports() throws Exception {
        JdbcTemplate jdbc = PostgresqlJdbcTestSupport.freshJdbcTemplate("passport_equipment_query");
        DataSource dataSource = jdbc.getDataSource();
        jdbc.execute("CREATE TABLE objects (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL, address TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP)");
        jdbc.execute("CREATE TABLE object_passports (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, object_id BIGINT NOT NULL REFERENCES objects(id), passport_number TEXT, details TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP)");

        ObjectPassportPhotoModel photoModel = new ObjectPassportPhotoModel(
                name -> "/api/object_passports/photos/" + name);
        ObjectPassportPayloadModel payloadModel = new ObjectPassportPayloadModel(photoModel);
        ObjectPassportPersistence persistence = new ObjectPassportPersistence(new ObjectMapper(), payloadModel);
        ObjectPassportEquipmentCatalogQuery query = new ObjectPassportEquipmentCatalogQuery(persistence);

        try (Connection connection = dataSource.getConnection()) {
            connection.setAutoCommit(false);

            Map<String, Object> first = new LinkedHashMap<>();
            first.put("department", "Dept A");
            first.put("equipment", List.of(
                    equipment("Router", "Acme", "X100", "11", false, "Power supply"),
                    equipment("router", "ACME", "x100", 12L, false, ""),
                    equipment("Switch", "Acme", "S1", 21L, true, "")));
            long firstObjectId = persistence.insertObject(connection, first);
            persistence.insertPassport(connection, firstObjectId, first);

            Map<String, Object> second = new LinkedHashMap<>();
            second.put("department", "Dept B");
            second.put("equipment", List.of(
                    equipment("ROUTER", "acme", "X100", 11L, false, ""),
                    equipment("Router", "Acme", "", 99L, false, "")));
            long secondObjectId = persistence.insertObject(connection, second);
            persistence.insertPassport(connection, secondObjectId, second);
            connection.commit();

            List<Map<String, Object>> candidates = query.listCandidates(connection);
            assertThat(candidates).hasSize(1);
            Map<String, Object> candidate = candidates.get(0);
            assertThat(candidate)
                    .containsEntry("equipment_type", "Router")
                    .containsEntry("equipment_vendor", "Acme")
                    .containsEntry("equipment_model", "X100")
                    .containsEntry("accessories", "Power supply")
                    .containsEntry("usage_count", 3)
                    .containsEntry("object_count", 2)
                    .containsEntry("discovered", true)
                    .containsEntry("source", "passports")
                    .containsEntry("photo_url", "")
                    .containsEntry("serial_number", "");
            Object rawCatalogIds = candidate.get("catalog_ids");
            assertThat(rawCatalogIds).isInstanceOf(List.class);
            List<?> catalogIds = (List<?>) rawCatalogIds;
            assertThat(catalogIds).hasSize(2);
            assertThat(catalogIds.get(0)).isEqualTo(11L);
            assertThat(catalogIds.get(1)).isEqualTo(12L);
        }
    }

    private Map<String, Object> equipment(String type,
                                          String vendor,
                                          String model,
                                          Object catalogId,
                                          boolean archived,
                                          String accessories) {
        LinkedHashMap<String, Object> item = new LinkedHashMap<>();
        item.put("equipment_type", type);
        item.put("vendor", vendor);
        item.put("model", model);
        item.put("catalog_id", catalogId);
        item.put("archived", archived);
        item.put("accessories", accessories);
        return item;
    }
}
