package com.example.panel.passports;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import com.fasterxml.jackson.databind.ObjectMapper;
import java.sql.Connection;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import javax.sql.DataSource;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

class ObjectPassportCreateCommandTest {

    @Test
    void createsObjectAndPassportAndPreservesValidation() throws Exception {
        DataSource dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:passport_create_command_" + System.nanoTime()
                        + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1",
                "sa",
                "");
        JdbcTemplate jdbc = new JdbcTemplate(dataSource);
        jdbc.execute("CREATE TABLE objects (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(255), address VARCHAR(255), created_at VARCHAR(64))");
        jdbc.execute("CREATE TABLE object_passports (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, object_id BIGINT, passport_number VARCHAR(255), details CLOB, created_at VARCHAR(64))");

        ObjectPassportPhotoModel photoModel = new ObjectPassportPhotoModel(name -> "/photos/" + name);
        ObjectPassportPayloadModel payloadModel = new ObjectPassportPayloadModel(photoModel);
        ObjectPassportPersistence persistence = new ObjectPassportPersistence(new ObjectMapper(), payloadModel);
        ObjectPassportCreateCommand command = new ObjectPassportCreateCommand(persistence, payloadModel);

        try (Connection connection = dataSource.getConnection()) {
            connection.setAutoCommit(false);
            Map<String, Object> payload = new LinkedHashMap<>();
            payload.put("business", "Business A");
            payload.put("city", "City A");
            payload.put("department", "Dept A");
            payload.put("location_address", "Main 1");
            payload.put("photos", List.of(Map.of(
                    "id", "photo-1",
                    "category", "title",
                    "stored_name", "front.jpg")));

            Map<String, Object> result = command.create(connection, payload);
            assertThat(connection.getAutoCommit()).isFalse();
            assertThat(result).containsEntry("success", true);
            assertThat(result.get("id")).isInstanceOf(Number.class);
            long passportId = ((Number) result.get("id")).longValue();
            Object rawPassport = result.get("passport");
            assertThat(rawPassport).isInstanceOf(Map.class);
            @SuppressWarnings("unchecked")
            Map<String, Object> passport = (Map<String, Object>) rawPassport;
            assertThat(passport)
                    .containsEntry("id", passportId)
                    .containsEntry("is_new", false)
                    .containsEntry("business", "Business A")
                    .containsEntry("city", "City A")
                    .containsEntry("department", "Dept A");
            connection.commit();

            assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM objects", Integer.class)).isEqualTo(1);
            assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM object_passports", Integer.class)).isEqualTo(1);
            assertThat(jdbc.queryForObject("SELECT passport_number FROM object_passports WHERE id = ?", String.class, passportId))
                    .isEqualTo("Dept A");

            assertThatThrownBy(() -> command.create(connection, Map.of("city", "City B")))
                    .isInstanceOf(IllegalArgumentException.class)
                    .hasMessage("Поле «Департамент» обязательно для заполнения.");
            connection.rollback();
            assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM objects", Integer.class)).isEqualTo(1);
            assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM object_passports", Integer.class)).isEqualTo(1);
        }
    }
}
