package com.example.panel.passports;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import com.fasterxml.jackson.databind.ObjectMapper;
import java.sql.Connection;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import javax.sql.DataSource;
import org.junit.jupiter.api.Test;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.web.server.ResponseStatusException;

class ObjectPassportCasesQueryTest {

    @Test
    void loadsNormalizedPassportContextAndProjectsDeduplicatedCases() throws Exception {
        DataSource dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:passport_cases_query_" + System.nanoTime()
                        + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1",
                "sa",
                "");
        JdbcTemplate jdbc = new JdbcTemplate(dataSource);
        jdbc.execute("CREATE TABLE objects (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(255), address VARCHAR(255), created_at VARCHAR(64))");
        jdbc.execute("CREATE TABLE object_passports (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, object_id BIGINT, passport_number VARCHAR(255), details CLOB, created_at VARCHAR(64))");
        jdbc.execute("CREATE TABLE messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ticket_id VARCHAR(255), business VARCHAR(255), city VARCHAR(255), location_name VARCHAR(255), problem VARCHAR(2000), created_at VARCHAR(64))");

        ObjectPassportPhotoModel photoModel = new ObjectPassportPhotoModel(name -> "/photos/" + name);
        ObjectPassportPayloadModel payloadModel = new ObjectPassportPayloadModel(photoModel);
        ObjectPassportPersistence persistence = new ObjectPassportPersistence(new ObjectMapper(), payloadModel);
        ObjectPassportAppealQuery appealQuery = new ObjectPassportAppealQuery(jdbc);
        ObjectPassportCasesQuery query = new ObjectPassportCasesQuery(persistence, payloadModel, appealQuery);

        long passportId;
        try (Connection connection = dataSource.getConnection()) {
            connection.setAutoCommit(false);
            Map<String, Object> payload = new LinkedHashMap<>();
            payload.put("business", "Business A");
            payload.put("city", "City A");
            payload.put("department", "Dept A");
            long objectId = persistence.insertObject(connection, payload);
            passportId = persistence.insertPassport(connection, objectId, payload);
            connection.commit();

            jdbc.update("INSERT INTO messages(ticket_id,business,city,location_name,problem,created_at) VALUES (?,?,?,?,?,?)", "T-1", "Business A", "City A", "Dept A", "older", "2026-09-16T10:00:00");
            jdbc.update("INSERT INTO messages(ticket_id,business,city,location_name,problem,created_at) VALUES (?,?,?,?,?,?)", "T-1", "Business A", "City A", "Dept A", "newer", "2026-09-16T11:00:00");
            jdbc.update("INSERT INTO messages(ticket_id,business,city,location_name,problem,created_at) VALUES (?,?,?,?,?,?)", "T-2", "Business A", "City A", "Dept A", "second", "2026-09-16T12:00:00");

            Map<String, Object> result = query.load(connection, passportId);
            assertThat(result)
                    .containsEntry("success", true)
                    .containsEntry("total_count", 2)
                    .containsEntry("total_minutes", 0)
                    .containsEntry("total_display", "0 мин");

            Object rawItems = result.get("items");
            assertThat(rawItems).isInstanceOf(List.class);
            List<?> items = (List<?>) rawItems;
            assertThat(items).hasSize(2);
            assertThat(((Map<?, ?>) items.get(0)).get("ticket_id")).isEqualTo("T-2");
            assertThat(((Map<?, ?>) items.get(1)).get("ticket_id")).isEqualTo("T-1");
            assertThat(((Map<?, ?>) items.get(1)).get("problem")).isEqualTo("newer");

            assertThatThrownBy(() -> query.load(connection, passportId + 1000))
                    .isInstanceOf(ResponseStatusException.class)
                    .satisfies(error -> assertThat(((ResponseStatusException) error).getStatusCode())
                            .isEqualTo(HttpStatus.NOT_FOUND));
        }
    }
}
