#!/bin/sh
set -eu
umask 077

bucket="${APP_STORAGE_OBJECT_BUCKET:?APP_STORAGE_OBJECT_BUCKET is required}"
root="/backup/offhost/minio"
snapshots="${root}/snapshots"
manifests="${root}/manifests"
success_file="${manifests}/.iguana-restore-evidence.properties"
failure_file="${manifests}/.iguana-restore-failure.properties"
attempt_at="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
succeeded=0
current_snapshot=""

write_failure() {
  code="$?"
  if [ "${succeeded}" -eq 1 ]; then
    return 0
  fi
  note="MinIO restore rehearsal failed"
  if [ -n "${current_snapshot}" ]; then
    note="${note}: $(basename "${current_snapshot}")"
  fi
  tmp="${failure_file}.tmp.$$"
  {
    printf 'status=error\n'
    printf 'attempt_at=%s\n' "${attempt_at}"
    printf 'note=%s\n' "${note}"
  } > "${tmp}"
  mv "${tmp}" "${failure_file}"
  exit "${code}"
}
trap write_failure EXIT INT TERM

current_snapshot="$(find "${snapshots}" -mindepth 1 -maxdepth 1 -type d | sort | tail -n 1)"
if [ -z "${current_snapshot}" ]; then
  echo "[ERROR] No MinIO backup snapshot found in ${snapshots}" >&2
  exit 1
fi

attempt=0
until mc alias set restore http://minio-restore-target:9000 restore-drill restore-drill-secret-only >/dev/null 2>&1; do
  attempt=$((attempt + 1))
  if [ "${attempt}" -ge 60 ]; then
    echo "[ERROR] Timed out waiting for isolated MinIO restore target" >&2
    exit 1
  fi
  sleep 2
done

mc mb --ignore-existing "restore/iguana-restore-drill" >/dev/null
mc mirror "${current_snapshot}/objects" "restore/iguana-restore-drill"

source_count="$(find "${current_snapshot}/objects" -type f | wc -l | tr -d '[:space:]')"
target_count="$(mc ls --recursive --json "restore/iguana-restore-drill" | grep -c '"type"[[:space:]]*:[[:space:]]*"file"' || true)"
if [ "${source_count}" != "${target_count}" ]; then
  echo "[ERROR] MinIO restore object count mismatch: source=${source_count}, target=${target_count}" >&2
  exit 1
fi

first_file="$(find "${current_snapshot}/objects" -type f | head -n 1 || true)"
if [ -n "${first_file}" ]; then
  relative="${first_file#${current_snapshot}/objects/}"
  expected_sha="$(sha256sum "${first_file}" | awk '{print $1}')"
  actual_sha="$(mc cat "restore/iguana-restore-drill/${relative}" | sha256sum | awk '{print $1}')"
  if [ "${expected_sha}" != "${actual_sha}" ]; then
    echo "[ERROR] MinIO restored sample checksum mismatch: ${relative}" >&2
    exit 1
  fi
fi

# Also validate an artifact generated by the backup package itself through the
# isolated object-storage target, proving the upload/download path end to end.
mc cp "${current_snapshot}/restore-sentinel.txt" "restore/iguana-restore-drill/.iguana-restore-sentinel.txt" >/dev/null
expected_sentinel_sha="$(sha256sum "${current_snapshot}/restore-sentinel.txt" | awk '{print $1}')"
actual_sentinel_sha="$(mc cat "restore/iguana-restore-drill/.iguana-restore-sentinel.txt" | sha256sum | awk '{print $1}')"
if [ "${expected_sentinel_sha}" != "${actual_sentinel_sha}" ]; then
  echo "[ERROR] MinIO backup package sentinel checksum mismatch" >&2
  exit 1
fi

verified_at="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
tmp="${success_file}.tmp.$$"
{
  printf 'status=ok\n'
  printf 'attempt_at=%s\n' "${attempt_at}"
  printf 'verified_at=%s\n' "${verified_at}"
  printf 'note=Automated MinIO restore rehearsal passed for snapshot %s; objects=%s\n' "$(basename "${current_snapshot}")" "${source_count}"
} > "${tmp}"
mv "${tmp}" "${success_file}"
rm -f "${failure_file}"
succeeded=1
trap - EXIT INT TERM

echo "[GREEN] MinIO isolated restore rehearsal passed: $(basename "${current_snapshot}"); objects=${source_count}"
