param(
    [switch]$Force,
    [switch]$SkipDocker,
    [switch]$ValidateOnly
)

$ErrorActionPreference = "Stop"

function Get-RepoRoot {
    if (-not $PSScriptRoot) {
        throw "Unable to resolve script root for bootstrap-first-run.ps1."
    }
    return [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot ".."))
}

function Test-PortBusy {
    param(
        [int]$Port
    )

    try {
        $listener = [System.Net.Sockets.TcpListener]::new([System.Net.IPAddress]::Loopback, $Port)
        $listener.Start()
        $listener.Stop()
        return $false
    } catch {
        return $true
    }
}

function Find-FreePort {
    param(
        [int]$StartPort
    )

    $candidate = $StartPort
    while (Test-PortBusy -Port $candidate) {
        $candidate++
    }
    return $candidate
}

function Test-DockerComposeAvailable {
    if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
        return $false
    }

    & docker compose version *> $null
    if ($LASTEXITCODE -ne 0) {
        return $false
    }

    & docker info *> $null
    return $LASTEXITCODE -eq 0
}

function Write-Utf8NoBomFile {
    param(
        [string]$Path,
        [string]$Content
    )

    $encoding = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($Path, $Content, $encoding)
}

function Ensure-Directory {
    param(
        [string]$Path
    )

    if (-not (Test-Path -LiteralPath $Path)) {
        New-Item -ItemType Directory -Path $Path | Out-Null
    }
}

function Build-EnvContent {
    param(
        [string]$Mode,
        [int]$PostgresPort,
        [string]$TransportMode,
        [int]$RabbitAmqpPort,
        [int]$RabbitHttpPort
    )

    $lines = @(
        "# Iguana first-run bootstrap",
        "# Generated by scripts/bootstrap-first-run.ps1",
        "IGUANA_BOOTSTRAP_DB_MODE=$Mode",
        "APP_POSTGRES_PORT=$PostgresPort",
        "APP_RABBITMQ_AMQP_PORT=$RabbitAmqpPort",
        "APP_RABBITMQ_HTTP_PORT=$RabbitHttpPort",
        ""
    )

    if ($Mode -eq "postgresql") {
        $lines += @(
            "APP_DB_MODE=postgresql",
            "SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:$PostgresPort/iguana",
            "SPRING_DATASOURCE_USERNAME=iguana",
            "SPRING_DATASOURCE_PASSWORD=iguana",
            ""
        )
    } else {
        $lines += @(
            "APP_DB_MODE=sqlite",
            ""
        )
    }

    $lines += @(
        "APP_INTEGRATION_TRANSPORT_MODE=$TransportMode",
        "SPRING_RABBITMQ_HOST=localhost",
        "SPRING_RABBITMQ_PORT=$RabbitAmqpPort",
        "SPRING_RABBITMQ_USERNAME=iguana",
        "SPRING_RABBITMQ_PASSWORD=iguana",
        ""
    )

    $lines += @(
        "APP_STORAGE_ATTACHMENTS=attachments",
        "APP_STORAGE_KNOWLEDGE_BASE=attachments/knowledge_base",
        "APP_STORAGE_AVATARS=attachments/avatars",
        "APP_STORAGE_WEBFORMS=attachments/forms",
        "APP_BOT_DATABASE_DIR=bot_databases",
        "APP_PANEL_LOG_DIR=logs",
        "APP_BOT_LOG_DIR=logs"
    )

    return ($lines -join [Environment]::NewLine) + [Environment]::NewLine
}

$repoRoot = Get-RepoRoot
$envFile = Join-Path $repoRoot ".env"
$composeFile = Join-Path $repoRoot "docker-compose.local-postgres.yml"
$bootstrapMode = [Environment]::GetEnvironmentVariable("IGUANA_BOOTSTRAP_DB_MODE")
if ([string]::IsNullOrWhiteSpace($bootstrapMode)) {
    $bootstrapMode = "auto"
}
$bootstrapMode = $bootstrapMode.Trim().ToLowerInvariant()

if ($bootstrapMode -notin @("auto", "sqlite", "postgresql")) {
    throw "Unsupported IGUANA_BOOTSTRAP_DB_MODE '$bootstrapMode'. Allowed values: auto, sqlite, postgresql."
}

$dockerAvailable = $false
if (-not $SkipDocker -and $bootstrapMode -ne "sqlite") {
    $dockerAvailable = Test-DockerComposeAvailable
}

$effectiveMode = switch ($bootstrapMode) {
    "postgresql" {
        if (-not $dockerAvailable -and -not $SkipDocker) {
            throw "IGUANA_BOOTSTRAP_DB_MODE=postgresql requires Docker with docker compose."
        }
        "postgresql"
    }
    "sqlite" { "sqlite" }
    default {
        if ($dockerAvailable) { "postgresql" } else { "sqlite" }
    }
}

$preferredPort = 5432
$effectivePort = if ($effectiveMode -eq "postgresql") { Find-FreePort -StartPort $preferredPort } else { $preferredPort }
$preferredRabbitAmqpPort = 5672
$preferredRabbitHttpPort = 15672
$effectiveRabbitAmqpPort = if ($effectiveMode -eq "postgresql") { Find-FreePort -StartPort $preferredRabbitAmqpPort } else { $preferredRabbitAmqpPort }
$effectiveRabbitHttpPort = if ($effectiveMode -eq "postgresql") { Find-FreePort -StartPort $preferredRabbitHttpPort } else { $preferredRabbitHttpPort }
$effectiveTransportMode = if ($effectiveMode -eq "postgresql") { "rabbitmq" } else { "jdbc" }

if ($ValidateOnly) {
    Write-Host "[INFO] Bootstrap validation succeeded."
    Write-Host "[INFO] Mode: $effectiveMode"
    if ($effectiveMode -eq "postgresql") {
        Write-Host "[INFO] PostgreSQL port: $effectivePort"
        Write-Host "[INFO] RabbitMQ AMQP port: $effectiveRabbitAmqpPort"
        Write-Host "[INFO] RabbitMQ HTTP port: $effectiveRabbitHttpPort"
    }
    Write-Host "[INFO] Transport mode: $effectiveTransportMode"
    exit 0
}

$directories = @(
    (Join-Path $repoRoot "attachments"),
    (Join-Path $repoRoot "attachments\knowledge_base"),
    (Join-Path $repoRoot "attachments\forms"),
    (Join-Path $repoRoot "attachments\avatars"),
    (Join-Path $repoRoot "logs"),
    (Join-Path $repoRoot "bot_databases")
)

foreach ($directory in $directories) {
    Ensure-Directory -Path $directory
}

if ((-not (Test-Path -LiteralPath $envFile)) -or $Force) {
    $envContent = Build-EnvContent `
        -Mode $effectiveMode `
        -PostgresPort $effectivePort `
        -TransportMode $effectiveTransportMode `
        -RabbitAmqpPort $effectiveRabbitAmqpPort `
        -RabbitHttpPort $effectiveRabbitHttpPort
    Write-Utf8NoBomFile -Path $envFile -Content $envContent
    Write-Host "[INFO] Created $envFile"
} else {
    Write-Host "[INFO] Keeping existing $envFile"
}

if ($effectiveMode -eq "postgresql" -and -not $SkipDocker) {
    Write-Host "[INFO] Starting local PostgreSQL and RabbitMQ via docker compose"
    & docker compose -f $composeFile up -d postgres rabbitmq
    if ($LASTEXITCODE -ne 0) {
        throw "Failed to start local PostgreSQL/RabbitMQ containers."
    }
    Write-Host "[INFO] Local PostgreSQL is starting on localhost:$effectivePort"
    Write-Host "[INFO] Local RabbitMQ is starting on localhost:$effectiveRabbitAmqpPort (management UI: http://localhost:$effectiveRabbitHttpPort)"
} elseif ($effectiveMode -eq "sqlite") {
    Write-Host "[INFO] Docker is unavailable, bootstrap stayed in SQLite+JDBC dev mode."
}

Write-Host "[INFO] First-run bootstrap completed."
