#!/usr/bin/env bash
set -euo pipefail

FORCE=0
SKIP_DOCKER=0
VALIDATE_ONLY=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --force)
      FORCE=1
      shift
      ;;
    --skip-docker)
      SKIP_DOCKER=1
      shift
      ;;
    --validate-only)
      VALIDATE_ONLY=1
      shift
      ;;
    *)
      echo "[ERROR] Unknown argument: $1" >&2
      exit 1
      ;;
  esac
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
ENV_FILE="${REPO_ROOT}/.env"
COMPOSE_FILE="${REPO_ROOT}/docker-compose.local-postgres.yml"
BOOTSTRAP_MODE="${IGUANA_BOOTSTRAP_DB_MODE:-auto}"

test_port_busy() {
  local port="$1"
  if command -v ss >/dev/null 2>&1; then
    ss -lnt "sport = :${port}" 2>/dev/null | grep -q ":${port} "
    return $?
  fi
  if command -v netstat >/dev/null 2>&1; then
    netstat -lnt 2>/dev/null | awk '{print $4}' | grep -q ":${port}$"
    return $?
  fi
  return 1
}

find_free_port() {
  local candidate="$1"
  while test_port_busy "${candidate}"; do
    candidate=$((candidate + 1))
  done
  echo "${candidate}"
}

docker_compose_available() {
  if [[ "${SKIP_DOCKER}" == "1" ]]; then
    return 1
  fi
  command -v docker >/dev/null 2>&1 || return 1
  docker compose version >/dev/null 2>&1 || return 1
  docker info >/dev/null 2>&1 || return 1
}

build_env_file() {
  local mode="$1"
  local port="$2"

  cat <<EOF
# Iguana first-run bootstrap
# Generated by scripts/bootstrap-first-run.sh
IGUANA_BOOTSTRAP_DB_MODE=${mode}
APP_POSTGRES_PORT=${port}

EOF

  if [[ "${mode}" == "postgresql" ]]; then
    cat <<EOF
APP_DB_MODE=postgresql
SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:${port}/iguana
SPRING_DATASOURCE_USERNAME=iguana
SPRING_DATASOURCE_PASSWORD=iguana

EOF
  else
    cat <<EOF
APP_DB_MODE=sqlite

EOF
  fi

  cat <<EOF
APP_STORAGE_ATTACHMENTS=attachments
APP_STORAGE_KNOWLEDGE_BASE=attachments/knowledge_base
APP_STORAGE_AVATARS=attachments/avatars
APP_STORAGE_WEBFORMS=attachments/forms
APP_BOT_DATABASE_DIR=bot_databases
APP_PANEL_LOG_DIR=logs
APP_BOT_LOG_DIR=logs
EOF
}

case "${BOOTSTRAP_MODE}" in
  auto|sqlite|postgresql)
    ;;
  *)
    echo "[ERROR] Unsupported IGUANA_BOOTSTRAP_DB_MODE: ${BOOTSTRAP_MODE}" >&2
    exit 1
    ;;
esac

DOCKER_AVAILABLE=0
if [[ "${BOOTSTRAP_MODE}" != "sqlite" ]] && docker_compose_available; then
  DOCKER_AVAILABLE=1
fi

case "${BOOTSTRAP_MODE}" in
  postgresql)
    if [[ "${DOCKER_AVAILABLE}" != "1" ]]; then
      echo "[ERROR] IGUANA_BOOTSTRAP_DB_MODE=postgresql requires Docker with docker compose." >&2
      exit 1
    fi
    EFFECTIVE_MODE="postgresql"
    ;;
  sqlite)
    EFFECTIVE_MODE="sqlite"
    ;;
  *)
    if [[ "${DOCKER_AVAILABLE}" == "1" ]]; then
      EFFECTIVE_MODE="postgresql"
    else
      EFFECTIVE_MODE="sqlite"
    fi
    ;;
esac

if [[ "${EFFECTIVE_MODE}" == "postgresql" ]]; then
  EFFECTIVE_PORT="$(find_free_port 5432)"
else
  EFFECTIVE_PORT="5432"
fi

if [[ "${VALIDATE_ONLY}" == "1" ]]; then
  echo "[INFO] Bootstrap validation succeeded."
  echo "[INFO] Mode: ${EFFECTIVE_MODE}"
  if [[ "${EFFECTIVE_MODE}" == "postgresql" ]]; then
    echo "[INFO] PostgreSQL port: ${EFFECTIVE_PORT}"
  fi
  exit 0
fi

mkdir -p \
  "${REPO_ROOT}/attachments" \
  "${REPO_ROOT}/attachments/knowledge_base" \
  "${REPO_ROOT}/attachments/forms" \
  "${REPO_ROOT}/attachments/avatars" \
  "${REPO_ROOT}/logs" \
  "${REPO_ROOT}/bot_databases"

if [[ ! -f "${ENV_FILE}" || "${FORCE}" == "1" ]]; then
  build_env_file "${EFFECTIVE_MODE}" "${EFFECTIVE_PORT}" > "${ENV_FILE}"
  echo "[INFO] Created ${ENV_FILE}"
else
  echo "[INFO] Keeping existing ${ENV_FILE}"
fi

if [[ "${EFFECTIVE_MODE}" == "postgresql" && "${SKIP_DOCKER}" != "1" ]]; then
  echo "[INFO] Starting local PostgreSQL via docker compose"
  docker compose -f "${COMPOSE_FILE}" up -d postgres
  echo "[INFO] Local PostgreSQL is starting on localhost:${EFFECTIVE_PORT}"
elif [[ "${EFFECTIVE_MODE}" == "sqlite" ]]; then
  echo "[INFO] Docker is unavailable, bootstrap stayed in SQLite dev mode."
fi

echo "[INFO] First-run bootstrap completed."
