#!/usr/bin/env bash
set -euo pipefail

FORCE=0
SKIP_DOCKER=0
VALIDATE_ONLY=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --force)
      FORCE=1
      shift
      ;;
    --skip-docker)
      SKIP_DOCKER=1
      shift
      ;;
    --validate-only)
      VALIDATE_ONLY=1
      shift
      ;;
    *)
      echo "[ERROR] Unknown argument: $1" >&2
      exit 1
      ;;
  esac
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
ENV_FILE="${REPO_ROOT}/.env"
COMPOSE_FILE="${REPO_ROOT}/docker-compose.local-postgres.yml"
BOOTSTRAP_MODE="${IGUANA_BOOTSTRAP_DB_MODE:-auto}"

test_port_busy() {
  local port="$1"
  if command -v ss >/dev/null 2>&1; then
    ss -lnt "sport = :${port}" 2>/dev/null | grep -q ":${port} "
    return $?
  fi
  if command -v netstat >/dev/null 2>&1; then
    netstat -lnt 2>/dev/null | awk '{print $4}' | grep -q ":${port}$"
    return $?
  fi
  return 1
}

find_free_port() {
  local candidate="$1"
  while test_port_busy "${candidate}"; do
    candidate=$((candidate + 1))
  done
  echo "${candidate}"
}

docker_compose_available() {
  if [[ "${SKIP_DOCKER}" == "1" ]]; then
    return 1
  fi
  command -v docker >/dev/null 2>&1 || return 1
  docker compose version >/dev/null 2>&1 || return 1
  docker info >/dev/null 2>&1 || return 1
}

generate_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
    return
  fi
  if [[ -r /dev/urandom ]]; then
    od -An -N32 -tx1 /dev/urandom | tr -d ' \n'
    return
  fi
  if command -v python3 >/dev/null 2>&1; then
    python3 - <<'PY'
import secrets
print(secrets.token_hex(32))
PY
    return
  fi
  echo "[ERROR] Unable to generate a secure bootstrap secret." >&2
  exit 1
}

generate_base64_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 32 | tr -d '\n'
    return
  fi
  if command -v python3 >/dev/null 2>&1; then
    python3 - <<'PY'
import base64
import secrets
print(base64.b64encode(secrets.token_bytes(32)).decode("ascii"))
PY
    return
  fi
  echo "[ERROR] Unable to generate a secure bootstrap base64 secret." >&2
  exit 1
}

is_valid_monitoring_master_key_payload() {
  local encoded="$1"
  if [[ -z "${encoded}" ]]; then
    return 1
  fi
  if command -v python3 >/dev/null 2>&1; then
    python3 - "${encoded}" <<'PY'
import base64
import sys
value = sys.argv[1].strip()
try:
    decoded = base64.b64decode(value)
except Exception:
    raise SystemExit(1)
raise SystemExit(0 if len(decoded) in (16, 24, 32) else 1)
PY
    return $?
  fi
  if command -v openssl >/dev/null 2>&1; then
    local decoded_length
    decoded_length="$(printf '%s' "${encoded}" | openssl base64 -d -A 2>/dev/null | wc -c | tr -d ' ')"
    [[ "${decoded_length}" == "16" || "${decoded_length}" == "24" || "${decoded_length}" == "32" ]]
    return $?
  fi
  return 1
}

resolve_monitoring_master_key_value() {
  local legacy_key_path="${REPO_ROOT}/config/shared/monitoring-credentials.key"
  if [[ -f "${legacy_key_path}" ]]; then
    local legacy_encoded
    legacy_encoded="$(tr -d '\r\n' < "${legacy_key_path}")"
    if [[ -n "${legacy_encoded}" ]]; then
      if ! is_valid_monitoring_master_key_payload "${legacy_encoded}"; then
        echo "[ERROR] Legacy monitoring credentials key is not valid Base64 AES material: ${legacy_key_path}" >&2
        exit 1
      fi
      printf 'base64:%s' "${legacy_encoded}"
      return
    fi
  fi
  printf 'base64:%s' "$(generate_base64_secret)"
}

build_env_file() {
  local mode="$1"
  local port="$2"
  local transport_mode="$3"
  local rabbit_amqp_port="$4"
  local rabbit_http_port="$5"
  local postgres_password rabbit_password redis_password object_access_key object_secret_key
  local internal_bot_api_token remember_me_key monitoring_master_key grafana_admin_password

  postgres_password="$(generate_secret)"
  rabbit_password="$(generate_secret)"
  redis_password="$(generate_secret)"
  object_access_key="$(generate_secret | cut -c1-24)"
  object_secret_key="$(generate_secret)"
  internal_bot_api_token="$(generate_secret)"
  remember_me_key="$(generate_secret)"
  monitoring_master_key="$(resolve_monitoring_master_key_value)"
  grafana_admin_password="$(generate_secret)"

  cat <<EOF
# Iguana first-run bootstrap
# Generated by scripts/bootstrap-first-run.sh
# Fresh-install secrets below are generated once for this .env.
# Existing persisted infrastructure credentials are not rotated automatically.
IGUANA_BOOTSTRAP_DB_MODE=${mode}
APP_POSTGRES_PORT=${port}
APP_RABBITMQ_AMQP_PORT=${rabbit_amqp_port}
APP_RABBITMQ_HTTP_PORT=${rabbit_http_port}

EOF

  cat <<EOF
APP_DB_MODE=postgresql
SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:${port}/iguana
SPRING_DATASOURCE_USERNAME=iguana
SPRING_DATASOURCE_PASSWORD=${postgres_password}
APP_COORDINATION_MODE=direct
APP_COORDINATION_REQUIRED_FOR_POSTGRESQL=false
APP_STORAGE_OBJECT_REQUIRED_FOR_POSTGRESQL=false

IGUANA_POSTGRES_DB=iguana
IGUANA_POSTGRES_USER=iguana
IGUANA_POSTGRES_PASSWORD=${postgres_password}
IGUANA_RABBITMQ_USER=iguana
IGUANA_RABBITMQ_PASSWORD=${rabbit_password}
IGUANA_REDIS_PASSWORD=${redis_password}
APP_STORAGE_OBJECT_BUCKET=iguana
APP_STORAGE_OBJECT_REGION=us-east-1
APP_STORAGE_OBJECT_KEY_PREFIX=iguana
APP_STORAGE_OBJECT_ACCESS_KEY=${object_access_key}
APP_STORAGE_OBJECT_SECRET_KEY=${object_secret_key}
APP_INTERNAL_BOT_API_TOKEN=${internal_bot_api_token}
APP_SECURITY_REMEMBER_ME_KEY=${remember_me_key}
MONITORING_CREDENTIALS_MASTER_KEY=${monitoring_master_key}
IGUANA_GRAFANA_ADMIN_USER=admin
IGUANA_GRAFANA_ADMIN_PASSWORD=${grafana_admin_password}

EOF

  cat <<EOF
APP_INTEGRATION_TRANSPORT_MODE=${transport_mode}
SPRING_RABBITMQ_HOST=localhost
SPRING_RABBITMQ_PORT=${rabbit_amqp_port}
SPRING_RABBITMQ_USERNAME=iguana
SPRING_RABBITMQ_PASSWORD=${rabbit_password}

# One-time legacy SQLite migration compatibility
IGUANA_LEGACY_SQLITE_AUTO_IMPORT=${IGUANA_LEGACY_SQLITE_AUTO_IMPORT:-false}

EOF

  cat <<EOF
APP_STORAGE_ATTACHMENTS=../attachments
APP_STORAGE_KNOWLEDGE_BASE=../attachments/knowledge_base
APP_STORAGE_AVATARS=../attachments/avatars
APP_STORAGE_WEBFORMS=../attachments/forms
APP_BOT_DATABASE_DIR=../bot_databases
APP_PANEL_LOG_DIR=../logs
APP_BOT_LOG_DIR=../logs
EOF
}

case "${BOOTSTRAP_MODE}" in
  auto|postgresql)
    ;;
  *)
    echo "[ERROR] Unsupported IGUANA_BOOTSTRAP_DB_MODE: ${BOOTSTRAP_MODE}" >&2
    exit 1
    ;;
esac

DOCKER_AVAILABLE=0
if docker_compose_available; then
  DOCKER_AVAILABLE=1
fi

case "${BOOTSTRAP_MODE}" in
  postgresql)
    if [[ "${DOCKER_AVAILABLE}" != "1" && "${SKIP_DOCKER}" != "1" ]]; then
      echo "[ERROR] IGUANA_BOOTSTRAP_DB_MODE=postgresql requires Docker with docker compose." >&2
      exit 1
    fi
    EFFECTIVE_MODE="postgresql"
    ;;
  *)
    if [[ "${DOCKER_AVAILABLE}" != "1" ]]; then
      echo "[ERROR] Docker is unavailable after bootstrap checks. First-run bootstrap requires PostgreSQL/RabbitMQ via docker compose." >&2
      exit 1
    fi
    EFFECTIVE_MODE="postgresql"
    ;;
esac

EFFECTIVE_PORT="$(find_free_port 5432)"
EFFECTIVE_RABBIT_AMQP_PORT="$(find_free_port 5672)"
EFFECTIVE_RABBIT_HTTP_PORT="$(find_free_port 15672)"
EFFECTIVE_TRANSPORT_MODE="rabbitmq"

if [[ "${VALIDATE_ONLY}" == "1" ]]; then
  echo "[INFO] Bootstrap validation succeeded."
  echo "[INFO] Mode: ${EFFECTIVE_MODE}"
  echo "[INFO] PostgreSQL port: ${EFFECTIVE_PORT}"
  echo "[INFO] RabbitMQ AMQP port: ${EFFECTIVE_RABBIT_AMQP_PORT}"
  echo "[INFO] RabbitMQ HTTP port: ${EFFECTIVE_RABBIT_HTTP_PORT}"
  echo "[INFO] Transport mode: ${EFFECTIVE_TRANSPORT_MODE}"
  exit 0
fi

mkdir -p \
  "${REPO_ROOT}/attachments" \
  "${REPO_ROOT}/attachments/knowledge_base" \
  "${REPO_ROOT}/attachments/forms" \
  "${REPO_ROOT}/attachments/avatars" \
  "${REPO_ROOT}/logs" \
  "${REPO_ROOT}/bot_databases"

if [[ ! -f "${ENV_FILE}" || "${FORCE}" == "1" ]]; then
  if [[ -f "${ENV_FILE}" && "${FORCE}" == "1" ]]; then
    echo "[WARN] Recreating an existing .env with --force rotates bootstrap secrets in the file only. Use this only for fresh installs or after an explicit persistent-volume migration/reset." >&2
  fi
  build_env_file \
    "${EFFECTIVE_MODE}" \
    "${EFFECTIVE_PORT}" \
    "${EFFECTIVE_TRANSPORT_MODE}" \
    "${EFFECTIVE_RABBIT_AMQP_PORT}" \
    "${EFFECTIVE_RABBIT_HTTP_PORT}" > "${ENV_FILE}"
  echo "[INFO] Created ${ENV_FILE}"
else
  echo "[INFO] Keeping existing ${ENV_FILE}"
fi

if [[ "${SKIP_DOCKER}" != "1" ]]; then
  echo "[INFO] Starting local PostgreSQL and RabbitMQ via docker compose"
  docker compose -f "${COMPOSE_FILE}" up -d postgres rabbitmq
  echo "[INFO] Local PostgreSQL is starting on localhost:${EFFECTIVE_PORT}"
  echo "[INFO] Local RabbitMQ is starting on localhost:${EFFECTIVE_RABBIT_AMQP_PORT} (management UI: http://localhost:${EFFECTIVE_RABBIT_HTTP_PORT})"
fi

echo "[INFO] First-run bootstrap completed."
