package com.example.panel.repository;

import com.example.panel.support.PostgresqlJdbcTestSupport;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;

class MonitoringCheckHistoryRepositoryTest {

    @Test
    void deleteOlderThanUsesPostgresqlTimestampBinding() {
        JdbcTemplate jdbcTemplate = PostgresqlJdbcTestSupport.freshJdbcTemplate("monitoring_history");
        jdbcTemplate.execute("""
            CREATE TABLE monitoring_check_history (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                monitor_kind TEXT NOT NULL,
                monitor_id BIGINT NOT NULL,
                check_kind TEXT NOT NULL,
                status TEXT,
                summary TEXT,
                details_excerpt TEXT,
                http_status INTEGER,
                duration_ms BIGINT,
                created_at TIMESTAMP WITH TIME ZONE NOT NULL
            )
            """);

        OffsetDateTime cutoff = OffsetDateTime.now(ZoneOffset.UTC).minusDays(30).withNano(0);
        OffsetDateTime expired = cutoff.minusHours(1).withOffsetSameInstant(ZoneOffset.ofHours(2));
        OffsetDateTime fresh = cutoff.plusHours(1).withOffsetSameInstant(ZoneOffset.ofHours(-2));
        jdbcTemplate.update(
            "INSERT INTO monitoring_check_history(monitor_kind, monitor_id, check_kind, created_at) VALUES (?, ?, ?, ?)",
            "rms", 1L, "network", expired
        );
        jdbcTemplate.update(
            "INSERT INTO monitoring_check_history(monitor_kind, monitor_id, check_kind, created_at) VALUES (?, ?, ?, ?)",
            "rms", 1L, "network", fresh
        );

        MonitoringCheckHistoryRepository repository = new MonitoringCheckHistoryRepository(jdbcTemplate);
        int deleted = repository.deleteOlderThan(cutoff);

        assertEquals(1, deleted);
        assertEquals(1, repository.findRecent("rms", 1L, 10).size());
    }
}
