package com.example.panel.repository;

import com.example.panel.support.PostgresqlJdbcTestSupport;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;

import java.time.OffsetDateTime;
import java.time.ZoneOffset;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

class RmsRefreshQueueRepositoryTest {

    @Test
    void enqueueUsesBooleanAndTimestampTypesCompatibleWithPostgresql() {
        JdbcTemplate jdbcTemplate = PostgresqlJdbcTestSupport.freshJdbcTemplate("rms_refresh_queue");
        jdbcTemplate.execute("""
            CREATE TABLE rms_refresh_queue (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                queue_kind VARCHAR(32) NOT NULL,
                monitor_id BIGINT,
                with_notifications BOOLEAN NOT NULL DEFAULT FALSE,
                status VARCHAR(32) NOT NULL,
                requested_at TIMESTAMP WITH TIME ZONE NOT NULL
            )
            """);

        RmsRefreshQueueRepository repository = new RmsRefreshQueueRepository(jdbcTemplate);
        OffsetDateTime requestedAt = OffsetDateTime.of(2026, 8, 18, 19, 0, 0, 0, ZoneOffset.UTC);

        RmsRefreshQueueRepository.RefreshQueueEntry created = repository.enqueue(
            RmsRefreshQueueRepository.KIND_LICENSE,
            42L,
            true,
            requestedAt
        );

        assertTrue(created.id() > 0L);
        assertTrue(created.withNotifications());

        RmsRefreshQueueRepository.RefreshQueueEntry loaded = repository
            .findNextActive(RmsRefreshQueueRepository.KIND_LICENSE)
            .orElseThrow();

        assertEquals(42L, loaded.monitorId());
        assertTrue(loaded.withNotifications());
        assertEquals(RmsRefreshQueueRepository.STATUS_QUEUED, loaded.status());
        assertEquals(requestedAt.toInstant(), loaded.requestedAt().toInstant());
    }
}
