CREATE TABLE IF NOT EXISTS rms_license_monitors (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    rms_address VARCHAR(512) NOT NULL,
    scheme VARCHAR(16) NOT NULL DEFAULT 'https',
    host VARCHAR(255) NOT NULL,
    port INT NOT NULL DEFAULT 443,
    auth_login VARCHAR(255) NOT NULL,
    auth_password TEXT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    server_name VARCHAR(255),
    server_type VARCHAR(128),
    server_version VARCHAR(128),
    license_status VARCHAR(32),
    license_error_message TEXT,
    license_expires_at TIMESTAMP NULL,
    license_days_left INT,
    license_last_checked_at TIMESTAMP NULL,
    license_last_notified_at TIMESTAMP NULL,
    rms_status VARCHAR(32),
    rms_status_message TEXT,
    ping_output LONGTEXT,
    traceroute_summary TEXT,
    traceroute_report LONGTEXT,
    traceroute_checked_at TIMESTAMP NULL,
    rms_last_checked_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY ux_rms_license_monitors_address (rms_address),
    KEY idx_rms_license_monitors_enabled (enabled)
);
